### ISSUE TITLE
It doesn't work on my computer

### ISSUE THREAD

**Issue by borland6** [sviatoslav-lebediev/anki-quizlet-importer-extended#1]
Hello, 

I got the following error messages while using importing my quizlet deck.
My quizlet deck URL is as following:
https://quizlet.com/tw/513398370/20200623-lesson-52-shelter-dog-flash-cards/

+++  error message begin +++

Anki 2.1.28 (7d8818f8) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-20 19:56:54

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Dennis\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 255, in onCode
    self.createDeck(deck)
  File "C:\Users\Dennis\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 289, in createDeck
    mw.col.decks.get(deck)["mid"] = model["id"]
  File "lib\site-packages\anki\decks.py", line 194, in get
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

+++ error message end +++

I tried both add-ons (with or without audio), but no luck.
I also tried to search in the google, but I can't find similar issue.
I have no idea how to fix it. Please kindly help me solve this issue.

Thanks for your great help in advance.
Dennis

**Comment by Takcaa** [comment]
Hey, 
I got the same issue. I reinstaled Anki, but not newest version, I instaled this one https://github.com/ankitects/anki/releases/tag/2.1.21

**Comment by borland6** [comment]
> Hey,
> I got the same issue. I reinstaled Anki, but not newest version, I instaled this one https://github.com/ankitects/anki/releases/tag/2.1.21

Hello Takcaa, 
Do you mean you fix this issue after reinstalled Anki 2.1.21?
If so, I will try to see if this could work for me.

Thank you.
Dennis

**Comment by Takcaa** [comment]
newest version is 2.1.28 and tool not work on that, but on 2.1.21 work well

**Comment by sviatoslav-lebediev** [comment]
it works right now on  2.1.28. Could you check it out?

**Comment by Takcaa** [comment]
It's working now 👍  Spasibo mate for this addon

**Comment by sviatoslav-lebediev** [comment]
@Takcaa sure, happy it works for you right now. Actually I haven't created it I've just added the audio support and stop/finish phrases :)

**Comment by sviatoslav-lebediev** [comment]
@borland6 could you please confirm that a new version of the plugin works on your computer?

**Comment by borland6** [comment]
@sviatoslav-lebediev 
I am sorry for my late response. It works now. Thanks for your great help.
