### ISSUE TITLE
quizlet add on

### ISSUE THREAD

**Issue by kimian97** [sviatoslav-lebediev/anki-quizlet-importer-extended#100]
Hello,  

I'm not able to add the quizlet-add on to my anki 
this is the error I'm getting: 
One or more errors occurred:

1362209126: Please check your internet connection. HTTPSConnectionPool(host='ankiweb.net', port=443): Max retries exceeded with url: /shared/download/1362209126?v=2.1&p=62 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

I even tried connecting to my hotspot but I still get the same error

**Comment by sviatoslav-lebediev** [comment]
Hi, it's 100% not related to this add-on, I would check your firewall configuration if you have any
Also you can try to install in manually from this URL https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/releases/tag/v2023.06.18
