### ISSUE TITLE
Standard error canceled due to error with "BackAudio"

### ISSUE THREAD

**Issue by jjm4000** [sviatoslav-lebediev/anki-quizlet-importer-extended#101]
**Describe the bug**

Error when trying to import deck

**Quizlet deck URL**

https://quizlet.com/kr/267460356/sogang-4a-unit-2-flash-cards/

**Additional context**

Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.4-arm64-arm-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-06-26 16:09:54
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'BackAudio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/name/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "/Users/name/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 435, in createDeck
    note["BackAudio"] = "[sound:" + file_name + "]"
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'BackAudio'

**Comment by sviatoslav-lebediev** [comment]
Hi, 99% that's the same issue https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/71#issuecomment-1529112844
please take a look and let me know if it fixes your problem

**Comment by jjm4000** [comment]
It did work, thank you so much!
I think it's worth mentioning that renaming it also fixes the issue though, since it seems like deleting the note type deletes all cards under that type as well.

**Comment by sviatoslav-lebediev** [comment]
yep, I guess you are right. This is a note that the add-on creates and uses, so it should not be changed
