### ISSUE TITLE
Anki quizlet importer issue 

### ISSUE THREAD

**Issue by saraag17** [sviatoslav-lebediev/anki-quizlet-importer-extended#103]
the addd on was workin for me now i am getting this error code, not sure what to so 
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-12.6.7-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-07-10 08:35:11
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/saraagirges/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "/Users/saraagirges/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 420, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'FrontText'

**Comment by sviatoslav-lebediev** [comment]
Hi, please take a look at this comment https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/71#issuecomment-1529112844

**Comment by sviatoslav-lebediev** [comment]
But it better to rename that note type otherwise it will remove some cards

**Comment by saraag17** [comment]
What do you mean rename that note type?Sent from my iPhoneOn Jul 10, 2023, at 2:50 PM, sviatoslav-lebediev ***@***.***> wrote:﻿
But it better to rename that note type otherwise it will remove some cards

**Comment by saraag17** [comment]
Every time I try to change the note type it goes back to being basic. Not the basic quizlet extended. Sent from my iPhoneOn Jul 10, 2023, at 3:18 PM, sviatoslav-lebediev ***@***.***> wrote:﻿
I'm talking about this note type
This is the note type that this add-on creates and uses. You should not change this note type
Maybe you have adapted it for your needs and now the add-on can't import cards. So try to open Tools/Manage Note Types
and rename this note type. The add-on will create a Basic Quizlet Extended note type next time when you try to import some deck.

**Comment by saraag17** [comment]
Hi, I am having trouble with the quizlet add on, I was wondering if there was anything you can do to help me fix this?
