### ISSUE TITLE
error when importing- "sorry this deck is private"

### ISSUE THREAD

**Issue by RT2323** [sviatoslav-lebediev/anki-quizlet-importer-extended#104]
**Describe the bug**
when trying to import my flashcard set it says sorry, this deck is private :(. i have tried numerous times and it says the same thing and i'm not sure on what to do as i need access to my flashcards on anki quite soon. please help

**Quizlet deck URL** [
https://quizlet.com/gb/797824298/12-theroetical-frameworks-and-plate-movements-flash-cards/?funnelUUID=c779b5fa-1400-4368-89b6-cfe804c7a156
**Additional context**
Error from the addon window: same as stated before 

moreover, the add on doesn't look like the newly updated one for some reason it still looks like the old one

**Comment by sviatoslav-lebediev** [comment]
Hi, you can try to remove the add-on and install from here https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/releases/tag/v2023.06.18

**Comment by RT2323** [comment]
> Hi, you can try to remove the add-on and install from here https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/releases/tag/v2023.06.18

Hello, when i click on the link for the quizlet importer anki addon, my mac says it requires an app to open it which it then says it isn't available in my country.
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/139176876/b54ce17a-4f9f-4224-acad-ddf73ce1762b)

**Comment by RT2323** [comment]
actually i've got the improved version of it now somehow it's there so there's no problem anymore i can post here again if there is but thank you so much for making this! lifesaver!
