### ISSUE TITLE
What's going on with the source code?

### ISSUE THREAD

**Issue by boehs** [sviatoslav-lebediev/anki-quizlet-importer-extended#105]
Hello! This is a diff between the current source code and the version being distributed.

```diff
487,492c487
< def mapItems(jsonData):
<     studiableDocumentData = jsonData['studiableDocumentData']
<     setIdToDiagramImage = studiableDocumentData.get(
<         'setIdToDiagramImage', None)
<     studiableItems = studiableDocumentData.get(
<         'studiableItems', studiableDocumentData.get('studiableItem'))
---
> def mapItems(studiableItems, setIdToDiagramImage):
634a630,632
>                 studiableItems = None
>                 setIdToDiagramImage = None
> 
639a638,644
>                     if m:
>                         data = json.loads(m.group(1).strip())
>                         studiableDocumentData = data['studiableDocumentData']
>                         setIdToDiagramImage = studiableDocumentData.get(
>                             'setIdToDiagramImage', None)
>                         studiableItems = studiableDocumentData.get(
>                             'studiableItems', studiableDocumentData.get('studiableItem'))
645a651,657
>                     if m:
>                         data = json.loads(m.group(1).strip())
>                         studiableDocumentData = data['studiableDocumentData']
>                         setIdToDiagramImage = studiableDocumentData.get(
>                             'setIdToDiagramImage', None)
>                         studiableItems = studiableDocumentData.get(
>                             'studiableItems', studiableDocumentData.get('studiableItem'))
647c659,671
<                 data = m.group(1).strip()
---
>                 if not m:
>                     regex = re.escape('dehydratedReduxStateKey":')
>                     regex += r'(.+?)'
>                     regex += re.escape('},"__N_SSP')
>                     m = re.search(regex, page_html)
>                     rawData = m.group(1).strip()
>                     data = json.loads(json.loads(rawData))
>                     studiableItems = data["studyModesCommon"]["studiableData"]["studiableItems"]
>                     setIdToDiagramImage = data["studyModesCommon"]["studiableData"]["setIdToDiagramImage"]
> 
>                 if not studiableItems:
>                     raise Exception("Can't extract data")
> 
649c673,674
<                 self.results['items'] = mapItems(json.loads(data))
---
>                 self.results['items'] = mapItems(
>                     studiableItems, setIdToDiagramImage)
653a679
> 
659a686
> 
660a688
> 
679c707
<                 if proxyRetry == True:
---
>                 if proxyRetry == True and not self.html:
706a735
> 
```

As far as I can tell, the visible source is out of date.

What I'm also curious about is `https://quizlet-proxy.proto.click/quizlet-deck?url=`. I can't find any information on proto.click, let alone the source code of this proxy. Do you control this domain?

Thank you!

**Comment by boehs** [comment]
I ask this mostly because we are interested in offering quizlet imports in another project, and we're struggling with, presumably, the same issue as

![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/51836263/2476698b-a5db-4a85-ad31-33b1dfe8708d)

**Comment by sviatoslav-lebediev** [comment]
Hi
1. I guess I've forgotten to do `git push` :) It's done. Take a look and let me know if you still see any differences
2. as for `https://quizlet-proxy.proto.click/quizlet-deck?url=` - yes, it's my fallback service, some users can't download HTML from Quizlet directly because of some network issues, this service tries to help them :)

**Comment by boehs** [comment]
> es, it's my fallback service, some users can't download HTML from Quizlet

yeah, we're having trouble getting around quizlet's bot filter, so seeing the proxy source code would be helpful?

**Comment by sviatoslav-lebediev** [comment]
I see, I need to take a look because I'm not sure I have a repo for that service.
but in a nutshell, I just use proxies from https://webshare.io and https://github.com/apify/got-scraping

**Comment by boehs** [comment]
Oh got it, more 3rd parties!! Thank you, this is very helpful. We're currently using scrapperapi, got-scraping looks very promising. Closing this issue out, might make sense to add the service to this repo eventually. Have a nice day :)
