### ISSUE TITLE
Import will not start

### ISSUE THREAD

**Issue by minimoth28** [sviatoslav-lebediev/anki-quizlet-importer-extended#109]
**Describe the bug**
The deck will create, but it will go no further. I have browsed through here, at comments 108 and 106 and tried the "Skip Errors" box, which has done nothing.

I have also tried the HTML fixes, both short and long links, and neither have fixed the issue. The add-on worked the first time I attempted to use it, but never since.

**Quizlet deck URL**
https://quizlet.com/330787911/flashcards?funnelUUID=ba80f5de-e908-493f-ab1d-42d16dee805a

**Additional context**
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the [add-ons section](https://forums.ankiweb.net/c/add-ons/11) of our support site. 
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-07-27 18:27:18

Caught exception:
Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\*****\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "C:\Users\*****\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 420, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'FrontText'

**Comment by sviatoslav-lebediev** [comment]
Hi, url should be https://quizlet.com/gb/330787911/aqa-gcse-biology-paper-1-flash-cards/
If you still have a problem - try to rename `Basic Quizlet Extended` note type

**Comment by minimoth28** [comment]
Renaming the note type has worked, thank you for your help.

**Comment by sviatoslav-lebediev** [comment]
Hi, it means that you have changed the `Basic Quizlet Extended` note type. Don't do this, the add-on uses this not type, so the structure should be the same. I would recommend after the import changing the Note type for imported cards.
