### ISSUE TITLE
Cannot find reverse card

### ISSUE THREAD

**Issue by j-j-kam** [sviatoslav-lebediev/anki-quizlet-importer-extended#11]
Unfortunately, I cannot find the reverse card - the deck contains only the front - back card and not back-front. It says in the addon specification that 2 cards are being created: original and reverse. Where can the reversed be stored? Overall the addon is splendiferous!

**Comment by sviatoslav-lebediev** [comment]
Hi, we create 2 templates, not 2 cards. You have everything that you need for creating a reversed cards 
Here is a video of how to work with templates https://www.youtube.com/watch?v=DnbKwHEQ1mA&yt:cc=on
or
* you can fill the `Add Reverse` field for required notes and it should create reversed items
* If you always want to have a reversed items you can go Tools->Note types select Basic Quizlet Extended -> click on cards
select a second template -> remove `{{#Add Reverse}}` and `{{/Add Reverse}}` -> save
