### ISSUE TITLE
Quizlet Importer not importing entire quizlet deck

### ISSUE THREAD

**Issue by seanster101** [sviatoslav-lebediev/anki-quizlet-importer-extended#112]
I am trying to upload a deck of 268 cards which was created by another Quizlet user. I made a copy of the deck in my own account and made it public. When I paste the link into the downloader on Anki, it finds the deck, but stops at 25/268 cards. I have removed the add-on and re-added it multiple times, I have tried doing it with and without audio, I have tried doing it with just the URL and then also with the HTML from View Page Source. None of these things get it to import the entire deck, or anything more than 25 cards. I am hoping to get some assistance with this please. 

Quizlet deck URL: https://quizlet.com/817213521/flashcards

Anki Version: 2.1.65 (aa9a734f)⁩
Mac Software: Ventura 13.4.1

This is what I see:
<img width="590" alt="image" src="https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/141772753/2d8e5892-93d4-45e1-b701-12ed935270da">

**Comment by sviatoslav-lebediev** [comment]
Hi try to check the `Skip errors` checkbox
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/97069d37-a486-4773-be48-9f2db2064f2d)

**Comment by seanster101** [comment]
Thanks so much. That worked.On Aug 10, 2023, at 5:30 AM, sviatoslav-lebediev ***@***.***> wrote:﻿
Hi try to check the Skip errors checkbox
