### ISSUE TITLE
anki error using import from quizlet add on. Successfully able to add on 2 decks ( not my own). Audio for the download deck important for language learning.

### ISSUE THREAD

**Issue by asinikwe** [sviatoslav-lebediev/anki-quizlet-importer-extended#113]
*Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-08-14 16:51:00

Caught exception:
Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'BackAudio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "C:\Users\Owner\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 435, in createDeck
    note["BackAudio"] = "[sound:" + file_name + "]"
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'BackAudio'
*Describe the bug**
A description of what the bug is.

**Quizlet deck URL**

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Hi, take a look at this comment  https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/71#issuecomment-1529112844
