### ISSUE TITLE
says a public deck is private

### ISSUE THREAD

**Issue by fallaciousfantasyfox** [sviatoslav-lebediev/anki-quizlet-importer-extended#116]
i tried to add this deck but the addon window said it was private when it is not. i've turned skip errors on and off

[**Quizlet deck URL**](https://quizlet.com/72275092/food-flash-cards/)

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Hi, I can't reproduce. I've tried to import and it looks like it works
here is your deck
[Food.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/12501046/Food.apkg.zip)
