### ISSUE TITLE
I did the hmtl thing and it still is showing up a bug code

### ISSUE THREAD

**Issue by TeddyCoding** [sviatoslav-lebediev/anki-quizlet-importer-extended#118]
it sent this big paragraph of code i tired with the hmtl without it i thought it was the ownership that was the problem everything I've tried doesn't work

https://quizlet.com/827074206/myers-psychology-for-ap-2e-unit-01-flash-cards/

**Additional context**
Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Captcha Challenge…</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16"

**Comment by sviatoslav-lebediev** [comment]
Hi, usually it means that something is wrong with the network, cloudflare decides that it needs to protect the quizlet url. I've tried to import that deck and haven't seen any issues :( 
But it's strange that the `html` option didn't work because it doesn't call any external resources. Have you unchecked `Download audio` ?

p.s. I've tried using the `HTML` flow as well and it worked.
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/31534808-7054-4975-b093-772369928d1b)


[Myers Psychology for AP 2e - Unit 01.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/12642710/Myers.Psychology.for.AP.2e.-.Unit.01.apkg.zip)

**Comment by Linh2990** [comment]
I try many time with HTML but...
Lỗi
Đã xảy ra lỗi. Vui lòng khởi động Anki trong khi giữ phím shift, điều này sẽ tạm thời vô hiệu hóa các tiện ích bạn đã cài đặt.
Nếu sự cố chỉ xảy ra khi bật tiện ích, vui lòng sử dụng Công cụ > Danh mục Tiện ích để tắt một số tiện ích và khởi động lại Anki, lặp lại cho đến khi bạn phát hiện ra tiện ích đang gây ra sự cố.
Khi bạn phát hiện ra tiện ích bổ sung đang gây ra sự cố, vui lòng báo cáo sự cố trên trang tiện ích.
Thông tin gỡ lỗi:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.14393
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-10-01 21:19:54

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 438, in createDeck
    file_name = self.fileDownloader(item["imageUrl"])
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 480, in fileDownloader
    raise e
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 410: Gone

**Comment by sviatoslav-lebediev** [comment]
try to check this checkbox

![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/dbd6f8aa-b83e-4549-aa43-13dc01d23fef)

**Comment by sviatoslav-lebediev** [comment]
also take a look at https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/103#issuecomment-1629578103

**Comment by Linh2990** [comment]
I tried. I think that it's scerity from Quizlet because I imported 59 cards from total 298 cards. I send link below, could you check for me?
https://quizlet.com/vn/818084095/review-tong-hop-odi3-flash-cards/

**Comment by sviatoslav-lebediev** [comment]
Sure, I've checked, for some reason I had a captcha error so I've switched to the 'HTML' mode.
But as you can see I've imported 298 cards.

![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/9af01d69-ceba-4b4b-a6e1-a58d9d5fef3c)
[Review tổng hợp Odi3.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/12793415/Review.t.ng.h.p.Odi3.apkg.zip)

**Comment by Linh2990** [comment]
Thanks! I got it
