### ISSUE TITLE
Add-on not importing audio on reverse of card. 

### ISSUE THREAD

**Issue by cityunpacked** [sviatoslav-lebediev/anki-quizlet-importer-extended#12]
Thanks for your very helpful add-on. After the latest update it is not importing audio on the reverse of cards, only the front. The set in question is here: https://quizlet.com/190436922/phrases-for-religious-visa-flash-cards/

**Comment by sviatoslav-lebediev** [comment]
Hi, I will take a look

**Comment by sviatoslav-lebediev** [comment]
I've fixed this issue. try to update a plugin version
