### ISSUE TITLE
Repetitive crash

### ISSUE THREAD

**Issue by philb64** [sviatoslav-lebediev/anki-quizlet-importer-extended#120]
Hi,
when trying to import https://quizlet.com/819982185/hsk-4-new-words-flash-cards/ I keep getting this error message below. Can you please help?
PS: I just LOVE your add-on, it is so useful to me. Thank you so much for your hard work.

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-26 16:47:06

Caught exception:
Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'BackText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\phili\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "C:\Users\phili\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 421, in createDeck
    note["BackText"] = item["definition"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'BackText'

**Comment by sviatoslav-lebediev** [comment]
Hi 99% that you have edited the "system" note type, the add-on uses this note time for the import process. More here https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/103#issuecomment-1629578103

**Comment by philb64** [comment]
Hi,

Effectively, that was the issue. Thanks a lot!

Best regards,

Philippe
