### ISSUE TITLE
Imports definition as the front text rather than the back text

### ISSUE THREAD

**Issue by ldtyrannus** [sviatoslav-lebediev/anki-quizlet-importer-extended#121]
**Describe the bug**
A description of what the bug is.
Upon importing a deck the front text being used is the definition in Quizlet rather than the term.

**Quizlet deck URL**
https://quizlet.com/623959152/flashcards
**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Hi, I don't think that the add-on issue, please take a look at this comment https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/120#issuecomment-1737159578
