### ISSUE TITLE
Import function stopped working today 

### ISSUE THREAD

**Issue by jeonkjc** [sviatoslav-lebediev/anki-quizlet-importer-extended#125]
**Describe the bug**
A description of what the bug is.

**Quizlet deck URL**

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
could you please provide some context otherwise i will not be able to help you.

**Comment by jeonkjc** [comment]
thank you so much for making the wonderful add-on! I think the Quizlet website was blocking me for ~15 mins. the import function started working again. :) thank you so much!

**Comment by sviatoslav-lebediev** [comment]
oh, cool, happy to help. If you see a captcha error you can try to use the HTML mode, here is a video https://vimeo.com/830860191
