### ISSUE TITLE
Broken in 23.10Qt6 fails to open

### ISSUE THREAD

**Issue by DoctorToBeIn23** [sviatoslav-lebediev/anki-quizlet-importer-extended#128]
Version 23.10 (3394ab02) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3 on macOS Ventura Version 13.3.1
Get the following error any time I select "Import from Quizlet" under tools

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (3394ab02) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.3.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-24 03:08:48
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 728, in runQuizletPlugin
    __window = QuizletWindow()
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 136, in __init__
    self.initGUI()
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 182, in initGUI
    self.text_url.setFocusPolicy(Qt.StrongFocus)
AttributeError: type object 'Qt' has no attribute 'StrongFocus'

**Comment by sviatoslav-lebediev** [comment]
hi, hm, I have never seen this issue before.
Looks like this is a new Anki version, right ? Could you please try to open `/Users/Jacob/Library/Application Support/Anki2/addons21/1362209126/init.py` and comment that line `182`? Does it work ?

**Comment by sviatoslav-lebediev** [comment]
And 1 more question - where did you take your Anki ?
I've downloaded from the site and the last version is  Version ⁨2.1.66 (70506aeb)⁩
but as I can see your version - Anki 23.10 
I guess it's some kind of a pre-release, right ?

**Comment by sviatoslav-lebediev** [comment]
have added a fix, try to update a plugin
