### ISSUE TITLE
when i press import from quizlet an error message appears

### ISSUE THREAD

**Issue by jnd4567** [sviatoslav-lebediev/anki-quizlet-importer-extended#130]
before i even would be able to paste the link in form my quizlet deck, an error message appears when i click import from quizlet

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-01 12:58:12
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\jesmi\AppData\Roaming\Anki2\addons21\Basic Quizlet Extended\__init__.py", line 728, in runQuizletPlugin
    __window = QuizletWindow()
  File "C:\Users\jesmi\AppData\Roaming\Anki2\addons21\Basic Quizlet Extended\__init__.py", line 136, in __init__
    self.initGUI()
  File "C:\Users\jesmi\AppData\Roaming\Anki2\addons21\Basic Quizlet Extended\__init__.py", line 182, in initGUI
    self.text_url.setFocusPolicy(Qt.StrongFocus)
AttributeError: type object 'Qt' has no attribute 'StrongFocus'

**Comment by sviatoslav-lebediev** [comment]
Hi, i guess it's related https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/128
You are using a beta version, right ?

**Comment by sviatoslav-lebediev** [comment]
have added a fix, try to update the add-on
