### ISSUE TITLE
Cannot run add-on - QSizePolicy issue

### ISSUE THREAD

**Issue by connor-hawley** [sviatoslav-lebediev/anki-quizlet-importer-extended#131]
Here's the full Anki error:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.6-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-01 22:42:43
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/hawlconn/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 731, in runQuizletPlugin
    __window = QuizletWindow()
  File "/Users/hawlconn/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 136, in __init__
    self.initGUI()
  File "/Users/hawlconn/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 279, in initGUI
    self.setSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
AttributeError: type object 'QSizePolicy' has no attribute 'Minimum'

this is the only add-on I'm running. please feel free to follow-up for more information

**Comment by sviatoslav-lebediev** [comment]
Hi, looks like this is because of the new anki version. I will take a look and will let you know. Thx for the report

**Comment by sviatoslav-lebediev** [comment]
it should be fixed, pls take a look and let me know if everything is ok

**Comment by connor-hawley** [comment]
yes, the fix worked. thank you so much! :)

**Comment by sviatoslav-lebediev** [comment]
cool, happy to help
