### ISSUE TITLE
To make it work, change Qt.StrongFocus to Qt.FocusPolicy.StrongFocus

### ISSUE THREAD

**Issue by nclvrps** [sviatoslav-lebediev/anki-quizlet-importer-extended#139]
**Describe the bug**
Qt.StrongFocus no longer works, it now needs to be Qt.FocusPolicy.StrongFocus. This change is also backwards compatible. Other Qt enums might also need to be changed, see https://doc.qt.io/qt-6/qt.html

**Quizlet deck URL**
none

**Additional context**
https://forums.ankiweb.net/t/porting-tips-for-anki-23-10/35916

**Comment by sviatoslav-lebediev** [comment]
Hi, is it the improvement request or it doesn't work at all? I have added a check for `Qt.StrongFocus` so I would expect it to work. If it's an improvement request and you know how to do this could you please add a PR ? I'm not a python dev and it will take time to add these changes
