### ISSUE TITLE
Audio Download doesn't download the audio from quizlet

### ISSUE THREAD

**Issue by chrikx** [sviatoslav-lebediev/anki-quizlet-importer-extended#14]
When I download this deck to anki, it gives a text to speech type audio, but the audio in the quizlet is a higher quality, pre-recorded human voice 

https://quizlet.com/422966295/bbg-chapter-06-flash-cards/

**Comment by sviatoslav-lebediev** [comment]
Hi, I will take a look, they have a few different audio URLs, maybe I need to take another one

**Comment by sviatoslav-lebediev** [comment]
@chrikx could you try to update a plugin ?

**Comment by chrikx** [comment]
Sure if you give me steps to do it

**Comment by sviatoslav-lebediev** [comment]
Tools->Add-ons - Check for updates
