### ISSUE TITLE
Error importing Quizlet deck into Anki. Add-on for quizlet is giving me an error. 

### ISSUE THREAD

**Issue by youcantoothit** [sviatoslav-lebediev/anki-quizlet-importer-extended#142]
I want to import this to anki deck. I went to add-ons and selected quizlet and selected the code and entered it in and now I can import to anki. I tried to copy and paste the URL for quizlet but I am getting an error and they wont transfer 

https://quizlet.com/861098002/final-exam-review-dht-flash-cards/?funnelUUID=0aef26c5-f6c2-4c4f-aab2-7ad64099dd7d

**Comment by sviatoslav-lebediev** [comment]
Hi could you please tell me what exactly doesn't work? I've tried to import your link and looks like everything is ok. If you see any errors try to check `Skip errors` checkbox

p.s. this is you anki deck 

[_____Final EXAM Review - DHT______.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/13628187/_____Final.EXAM.Review.-.DHT______.apkg.zip)

**Comment by MusmanK01** [comment]
Hello, when i try to import my decks they don't import and i get a error message saying Expecting value: line 1 column 1 (char 0). i have a list of quizlets that i want to import. 
https://quizlet.com/860102791/dat-bio-crash-1-3-notes-flash-cards/?i=zhs4t&x=1jqt
https://quizlet.com/860103069/bio-session-1-4-high-yield-questions-flash-cards/?i=zhs4t&x=1jqt
https://quizlet.com/860099461/qr-crash-course-flash-cards/?i=zhs4t&x=1jqt
https://quizlet.com/860100662/gc-high-yield-flash-cards/
https://quizlet.com/860100277/gen-chem-crash-course-2023-practice-questions-flash-cards/
https://quizlet.com/860101452/lab-tests-flash-cards/
https://quizlet.com/860101718/reactions-orgo-flash-cards/?i=zhs4t&x=1jqt
https://quizlet.com/860102085/dat-orgo-flash-cards/?i=zhs4t&x=1jqt

thank you!

**Comment by sviatoslav-lebediev** [comment]
Hi, it looks like they are all private. The add-on doesn't support private decks directly, but you can try to :
1. temporarily unprotect 1 deck and try to import
2. try to use HTML page mode. Here is a video https://vimeo.com/830860191

If you still see some errors, please post them here.
