### ISSUE TITLE
Error: can't find a deck with the ID 8

### ISSUE THREAD

**Issue by Nilgus** [sviatoslav-lebediev/anki-quizlet-importer-extended#15]
I have repeatedly tried to transfer the deck below from Quizlet to Anki.  Everytime Anki has told me it can't find it.

https://quizlet.com/_8rp2ld?x=1jqt&i=275fs5

**Comment by sviatoslav-lebediev** [comment]
Hi, could you try to use this URL https://quizlet.com/530248801/qasid-diplomasia-b1-chapter-4-lesson-1-flash-cards/ ?
