### ISSUE TITLE
[Error] Add a quizlet study set

### ISSUE THREAD

**Issue by archimpresson** [sviatoslav-lebediev/anki-quizlet-importer-extended#150]
**Describe the bug**
오류
오류가 발생했습니다. Shift 키를 누른 상태로 Anki를 재실행하십시오, 그러면 설치한 확장 프로그램을 임시로 비활성화합니다. 
만약 이 문제가 확장 프로그램이 활성화했을 때만 발생한다면, 도구 > 추가기능 메뉴를 사용해 일부 확장 프로그램을 비활성하고 Anki를 재실행하면 어떤 확장 프로그램이 문제를 발생하는지 찾을 수 있습니다.
어떤 확장 프로그램이 문제를 발생하는지 확인하셨다면, 해당 문제를 {-errors-addon-support-site} (지원사이트)의 확장 기능에 보고해 주십시오. 
디버그 정보:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-27 14:46:38
아마 관련 있는 확장 프로그램:⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'Image'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\archi\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "C:\Users\archi\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 440, in createDeck
    note["Image"] += '<div><img src="{0}"></div>'.format(
  File "anki.notes", line 159, in __getitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'Image'

**Quizlet deck URL**
https://quizlet.com/kr/866825279/hackers-toefl-vocabulary-day-4-to-6-flash-cards/

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Hi, please take a look at this comment https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/103#issuecomment-1629578103

p.s here is your deck 
[TOEFL Voca DAY 4 to 6.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/13777997/TOEFL.Voca.DAY.4.to.6.apkg.zip)

**Comment by archimpresson** [comment]
Hello, I really appreciate with your nice and quick response.
The issue happened due to my revision...
Thank you for making and maintaining this fantastic tool and responding to
users.
Hope God will be with you always in the rest your life.

Sincerely.

2023년 12월 27일 (수) 오후 8:02, sviatoslav-lebediev ***@***.***>님이
작성:
