### ISSUE TITLE
 failing to import any deck that i try

### ISSUE THREAD

**Issue by askasaskas** [sviatoslav-lebediev/anki-quizlet-importer-extended#153]
gives this error

Expecting value: line 1 column 1 (char 0) ----------------- <!DOCTYPE html> <html lang="en"> <head>     <meta charset="UTF-8">     <title>Captcha Challenge…</title>     <meta name="viewport" content="width=device-width,initial-scale=1">     <link rel="icon" type="image/png" sizes="16x16" href="data:image

thanks

**Comment by sviatoslav-lebediev** [comment]
If you constantly receive errors, try to enter Quizlet HTML manually, this approach you can try to use for private sets as well. Here you can watch how to do this https://vimeo.com/830860191 p.s you can also try to open that flashcards page in incognito mode and copy HTML from that page.

**Comment by sviatoslav-lebediev** [comment]
Please try now, it should work again.

**Comment by askasaskas** [comment]
thank you it works now. great work !
