### ISSUE TITLE
Failed import from quizlet

### ISSUE THREAD

**Issue by saraag17** [sviatoslav-lebediev/anki-quizlet-importer-extended#154]
when i try to import a deck from quizlet, I get this error code. 
![Screen Shot 2024-01-03 at 2 51 39 PM](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/139137274/bef5cadf-6623-442b-918c-5a73e94c89e8)

Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Captcha Challenge…</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16" href="data:image

**Comment by sviatoslav-lebediev** [comment]
If you constantly receive errors, try to enter Quizlet HTML manually, this approach you can try to use for private sets as well. Here you can watch how to do this https://vimeo.com/830860191 p.s you can also try to open that flashcards page in incognito mode and copy HTML from that page.

**Comment by saraag17** [comment]
I tried both options and it did not work, when I pressed view page source it was very long and I could not copy it all

**Comment by saraag17** [comment]
Is there something else I can do?

**Comment by saraag17** [comment]
Please, help me, this is the best way I study in school, is there anything you can do for me?

**Comment by sviatoslav-lebediev** [comment]
can you give me a deck url ?

**Comment by saraag17** [comment]
https://quizlet.com/867746167/hormonal-regulation-and-function-flash-cards/?funnelUUID=716efa85-47ef-4266-afc0-6df2df458c71

**Comment by sviatoslav-lebediev** [comment]
I've imported it in this way. Right now it's not possible to import audio :(

![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/43cf8d8e-402b-4df4-9080-4f20e41c382a)

this is your deck, you can download it and add to your anki

[Hormonal Regulation and Function.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/13823790/Hormonal.Regulation.and.Function.apkg.zip)

**Comment by saraag17** [comment]
I do not need the audio, just for it to be imported. Can you show me how you made it a zip to be able to import it into Anki please? Because this zip worked and it downloaded straight into Anki!

**Comment by sviatoslav-lebediev** [comment]
i've imported it to anki and after that 
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/d1f10157-7896-41fd-a7f2-2c68f8b0b2de)
it creates a *.apkg file, but GitHub does not allow uploading these files, so I just zipped that *.apkg file

**Comment by saraag17** [comment]
Oh, so how come it imports to anki when you do, but when I try to import it from quizlet it doesn’t allow me to, and gives me this error?

Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Captcha Challenge…</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="icon" type="image/png" sizes="16x16" href="data:image

**Comment by sviatoslav-lebediev** [comment]
try to use 'Open html', if you don't need audio it will work 100%
1. enter url
2. click open html
3. right click - > view page source (chrome)
4. ctrl + a or cmd+a (select all)
5. copy (ctrl+c or cmd+c)
6. paste to the anki
7. uncheck `Download audio` (you can also check `Skip errors`)
8. click import deck
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/5facf391-d8e0-4e88-a8f4-484a334d2581)

**Comment by saraag17** [comment]
YES, it did, thank you soooooooooo much!

**Comment by sviatoslav-lebediev** [comment]
sure, np, but I added some changes, you can try to import as always.
