### ISSUE TITLE
[ Error ] Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by archimpresson** [sviatoslav-lebediev/anki-quizlet-importer-extended#155]
**Describe the bug**

Please check the attached files including the error text.
[Expecting value line 1 column 1 (ch.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/13827431/Expecting.value.line.1.column.1.ch.txt)

**Quizlet deck URL**
https://quizlet.com/867930242/flashcards?funnelUUID=18737f48-22e2-4232-bf17-32ab4fda5b15

**Comment by sviatoslav-lebediev** [comment]
could you try now ?

**Comment by archimpresson** [comment]
Wow... it wokrs now!!!
You are surprisingly fast!!!
Thank you again and happy new year!!!

2024년 1월 4일 (목) 오후 5:09, sviatoslav-lebediev ***@***.***>님이
작성:

**Comment by sviatoslav-lebediev** [comment]
:) happy to help
