### ISSUE TITLE
Quizlet import not working

### ISSUE THREAD

**Issue by ElKron** [sviatoslav-lebediev/anki-quizlet-importer-extended#16]
Dear,

I always get the error below while trying to download a Russian <-> Dutch deck.
Quizlet link: https://quizlet.com/be/330117975/ruslan-russisch-les-1-flash-cards/

Kind regards, ElKron

Debug information:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-17 16:23:12

Caught exception:
Traceback (most recent call last):
  File "anki\notes.py", line 108, in _fieldOrd
KeyError: 'BackAudio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 302, in onCode
    self.createDeck(deck)
  File "C:\Users\xxxxx\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 358, in createDeck
    note["BackAudio"] = "[sound:" + file_name + "]"
  File "anki\notes.py", line 116, in __setitem__
  File "anki\notes.py", line 110, in _fieldOrd
KeyError: 'BackAudio'

**Comment by sviatoslav-lebediev** [comment]
Hi, thank you for letting me know. I've checked and it looks like everything is ok, I can import-export your deck.
Could you please take a look maybe you have changed a note type structure (Basic Quizlet Extended), or maybe you have used a plugin without audio support before (it has a different list of fields)? If so I would recommend to rename a note type and try to import again, the plugin will recreate a note type.


here is a list of words
![image](https://user-images.githubusercontent.com/19693768/96625296-a85ff000-1316-11eb-8995-61991eb1c6d4.png)

**Comment by ElKron** [comment]
renaming the note type worked like a charm. Thank you!
