### ISSUE TITLE
Quizlet to Anki Issue 

### ISSUE THREAD

**Issue by jrwe236** [sviatoslav-lebediev/anki-quizlet-importer-extended#163]
This add-on worked perfectly until about a week ago. I have copied the error code and screenshot of what it sent me when I have tried to import. Thank you so so much for you help!

Quizlet 
https://quizlet.com/871599997/anatomy-of-research-research-ethics-flash-cards/?funnelUUID=bd09a263-ec74-478c-b4d0-5bf35687badf

Screen shot 
<img width="775" alt="Screenshot 2024-01-17 at 12 28 57 PM" src="https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/156942985/410a5632-133b-497a-85ea-af8e6c969a5d">

Debug code
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-14.2.1-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Users/joshwest/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 486, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "/Users/joshwest/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 501, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joshwest/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "/Users/joshwest/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 437, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "/Users/joshwest/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 488, in fileDownloader
    if fallback and not fallback_call and self.config['license']:
KeyError: 'license'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Hyperlink ['318752047', 2023-06-18T07:39, 'None', '']
Advanced Browser ['874215009', 2023-10-21T10:34, 'None', '']
Anki Excel Sync ['1832015432', 2021-01-27T22:53, 'None', '']
BetterSearch ['1052724801', 2023-06-15T16:44, 'None', '']
Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-25T17:11, 'None', '']
Button Colours Good Again ['2494384865', 2022-09-27T06:18, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T11:06, 'None', '']
Extended Tag AddEdit Dialog ['1135507717', 2023-11-11T11:58, 'None', '']
Fastbar- with nightmode support ['46611790', 2023-06-27T07:47, 'None', '']
Frozen Fields ['516643804', 2020-02-29T23:12, 'None', '']
High Yield Tags ['1918380616', 2023-01-10T14:14, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Life Drain ['715575551', 2023-12-01T00:53, 'None', '']
More Overview Stats 21 ['738807903', 2021-07-30T15:13, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-14T12:12, 'None', '']
ReMemorize Rescheduler with sibling and logging v142 ['323586997', 2020-11-20T00:27, 'None', '']
Refocus Card when Reviewing 21 ['1642550423', 2018-09-19T10:14, 'None', '']
Remaining time for Anki 21 ['1508357010', 2020-12-13T09:14, '20.12.13i151', '']
Review Heatmap ['1771074083', 2022-07-13T05:08, 'None', '']

===IDs of active AnkiWeb add-ons===
1052724801 1135507717 1362209126 1374772155 1508357010 1642550423 1771074083 1832015432 1918380616 2494384865 318752047 323586997 46611790 516643804 594329229 715575551 738807903 831846358 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
Hi, I've released a new version of the add-on please update your version.
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/997dfbe4-3b06-4fd0-a958-bbf7cab8a701)
