### ISSUE TITLE
Tried the HTML, unchecked the audio, and everything but not working always says troubleshoot addon

### ISSUE THREAD

**Issue by GoldieShower** [sviatoslav-lebediev/anki-quizlet-importer-extended#169]
Link to quizlet: https://quizlet.com/61621486/umich-stomach-spleen-flash-cards/

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.4.1-arm64-arm-64bit

Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/name/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "/Users/lname/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 431, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'FrontText'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Hyperlink ['318752047', 2023-06-18T19:39, 'None', '']
Add Table ['1237621971', 2023-06-18T19:37, 'None', mod]
AnKing Note Types Easy Customization ['952691989', 2024-01-20T05:17, 'None', mod]
Batch Editing ['291119185', 2023-10-26T08:38, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T23:06, 'None', '']
Contanki - Controller Support for Anki beta ['1898790263', 2024-01-31T10:50, 'v0.11.5-beta', '']
Deck duplication ['1779572689', 2022-06-11T22:24, 'None', '']
Enhanced Cloze for Anki 21 ['1990296174', 2023-09-11T02:48, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T15:15, 'None', '']
Mac OSX Dictionary Lookup ['2059332871', 2023-10-19T06:22, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-16T02:55, 'None', '']
extended editor for field for tables searchreplace ['805891399', 2023-07-31T22:12, 'None', mod]

===IDs of active AnkiWeb add-ons===
1237621971 1362209126 1374772155 1779572689 1898790263 1990296174 2059332871 291119185 318752047 594329229 805891399 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
Hi, take a look at 4th item here https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ

**Comment by GoldieShower** [comment]
Anw, I have already solved it. Thank you!! I just deleted the note type and the add-on then re-downloaded the add-on.
