### ISSUE TITLE
403 error - other

### ISSUE THREAD

**Issue by strugglingstudentvibes** [sviatoslav-lebediev/anki-quizlet-importer-extended#171]
**Describe the bug**
Not sure if it's a bug [I'm very technilogically unadvanced especially for like coding etc.] but I can't uncheck the option for the audio support to get the quizlet to anki add on to work :(. 

**Quizlet deck URL**
https://quizlet.com/885446529/clin-med-pulmonology-lectures-1-2-flash-cards/?i=d1jt6&x=1jqt

**Additional context**
Error from the addon window
*It won't let me send my screen recording it says it's too big but here's at least a screenshot of what it shows me after it loads the add-on, like it won't give me that box to uncheck the audio support option. 
<img width="1512" alt="Screenshot 2024-02-25 at 11 47 43 AM" src="https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/161240633/029bd67e-1f5e-4778-8494-abde4f48005d">

**Comment by sviatoslav-lebediev** [comment]
Here is your deck without audio (if you need audio as well - let me know)
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/5c6905ad-fb7e-4649-b287-fa06d13cb5dd)
[Clin Med - Pulmonology Lectures 1-2.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/14397769/Clin.Med.-.Pulmonology.Lectures.1-2.apkg.zip)

**Comment by strugglingstudentvibes** [comment]
Oh my gosh I'm so sorry, it was straight up user error, it works perfectly thank you so much!!

**Comment by sviatoslav-lebediev** [comment]
no problem, happy that we have figured out :)
