### ISSUE TITLE
UNABLE TO UPLOAD QUIZLET TO ANKI

### ISSUE THREAD

**Issue by jbish90** [sviatoslav-lebediev/anki-quizlet-importer-extended#173]
**Describe the bug**
A description of what the bug is.
unknown error so will not import any of my cards
**Quizlet deck URL**
https://quizlet.com/gb/889402054/whole-of-theme-4-business-flash-cards/?new
**Additional context**
Error from the addon window
Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Captcha Challenge…</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16" href="data:image

**Comment by jbish90** [comment]
hope you can help?

**Comment by sviatoslav-lebediev** [comment]
Hi, please take a look at https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ

I would try to use an HTML mode, video is here https://vimeo.com/830860191

p.s. here is your deck
[WHOLE OF THEME 4 BUSINESS.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/14484789/WHOLE.OF.THEME.4.BUSINESS.apkg.zip)

**Comment by jbish90** [comment]
Good Evening
thank you so much for your help!! however, I'm still getting the error messages after watching the video despite your software normally always being so helpful it may be my fault.

 I know it's a big ask, but it would be so amazing and super helpful if there is any way you could send an attachment for four more Anki sets as I would greatly appreciate this for my studies.

Please let me know if this email reaches you, but I understand it may take some time to but it would save me so much rewriting my cards for my studies!

SME Topics 1/2/3 Flashcards | Quizlet<https://quizlet.com/gb/889958588/sme-topics-123-flash-cards/?funnelUUID=6b544fd0-1e41-4776-ae8f-1ac82f5bf6bf>
MOST OF THEME 3 Flashcards | Quizlet<https://quizlet.com/gb/889956726/most-of-theme-3-flash-cards/?funnelUUID=6582da5c-e0b2-4647-b1b1-59ed8d3550db>
WHOLE OF THEME 2 Flashcards | Quizlet<https://quizlet.com/gb/889949387/whole-of-theme-2-flash-cards/?funnelUUID=e90b9a4b-0ede-4190-a206-68d6f87841d4>
All chapters but 18/21 Flashcards | Quizlet<https://quizlet.com/gb/889960915/all-chapters-but-1821-flash-cards/?funnelUUID=9ef7b66e-d28b-41a0-96d6-51bcc2cfbc6a>

Many Thanks
James
________________________________

**Comment by sviatoslav-lebediev** [comment]
not a problem :)
here is you archive with all decks
[Archive.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/14486013/Archive.zip)

p.s. did you uncheck `Download audio` when you tried to import ?

**Comment by sviatoslav-lebediev** [comment]
going to close, open if you still have this problem
