### ISSUE TITLE
cant convert to anki deck due to quizlet having password

### ISSUE THREAD

**Issue by a-aroin** [sviatoslav-lebediev/anki-quizlet-importer-extended#174]
**Describe the bug**
i dont know if its a bug, but when i put in the url into the tool, it gives me an error. even when i turn on skip errors.

**Quizlet deck URL**
https://quizlet.com/888898752
**Additional context**
Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Captcha Challenge…</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

**Comment by sviatoslav-lebediev** [comment]
Hi this deck requires a password 
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/87d40c05-08df-4aa5-9111-6dc677d64085)
so I would recommend to use an HTML mode (video is here https://vimeo.com/830860191) or you can try to make it public, import, make it private

**Comment by sviatoslav-lebediev** [comment]
going to close, open if you still have this problem
