### ISSUE TITLE
Add-On Just Not Working

### ISSUE THREAD

**Issue by deirdreambrosi** [sviatoslav-lebediev/anki-quizlet-importer-extended#177]
I'm not sure what happened - all of my cards were fine, but then something didn't work with my AnkiWeb account so I uploaded my files *as is* to the AnkiWeb instead of downloading an earlier version that did sync to my AnkiWeb - and almost all of my cards imported from Quizlet deleted the back of the card. Further - I now keep getting an error message whenever I try to import any new quizlets. I've uninstalled and then re-installed the add-on, and followed all of the Anki instructions. 

I've been trying to upload many, but one of the Quizlet decks is: https://quizlet.com/737413999/medterm-chapter-7-flash-cards/?funnelUUID=b0311143-54b3-411a-b657-1e93759ea86b

This is the debug info: 
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.2.1-arm64-arm-64bit

Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/deirdreambrosi/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "/Users/deirdreambrosi/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 431, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'FrontText'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T13:55, 'None', '']
True Retention ['613684242', 2017-11-19T15:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126 1374772155 613684242

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
Hi, please take a look at https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ
4th item
