### ISSUE TITLE
Unable to have reverse card, after importing from quizlet to anki

### ISSUE THREAD

**Issue by lia3421** [sviatoslav-lebediev/anki-quizlet-importer-extended#179]
Even after changing note type to different ones, reverse card never added, or duplicated normal card. Unable to tick reverse audio box when importing as 403 error.
https://quizlet.com/gb/847305598/migration-and-diverse-society-flash-cards/?funnelUUID=04afb11e-2a66-4f2a-a3e2-d08e86a79630

**Comment by sviatoslav-lebediev** [comment]
Hi, 403 means that you can't download audio, if you need audio, please take a look at https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/discussions/156
Here is your deck, let me know if everything works with this one
[Migration and Diverse Society.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/14896815/Migration.and.Diverse.Society.apkg.zip)

**Comment by lia3421** [comment]
Hello
I do not need audio
Thank you though

**Comment by sviatoslav-lebediev** [comment]
if you don't need audio just uncheck a 'Download audio' checkbox or check the `Skip errors` checkbox
