### ISSUE TITLE
How to add reverse cards, or change the cards to reverse!

### ISSUE THREAD

**Issue by tonynap** [sviatoslav-lebediev/anki-quizlet-importer-extended#18]
Hello! I have what I suspect may be simple, but I cannot figure out how to do it.
Deck Used: https://quizlet.com/24957216/discover-china-book-1-unit-2-flash-cards/

I import a deck from quizlet fine, and now have for example 10 cards. I am importing Mandarin cards. An example card after import would be:

-----------------
Front: nihao 你好
Back: Hello
-----------------

Question is: How do I change the existing cards to the reverse? I would prefer the cards to be imported as follows
--------------
Front: Hello
Back: nihao 你好
--------------

From reading the documention, there exists a reverse card / template, but I don't understand how to create or change cards to that. **Ideally** I would be able to configure the addon to always **create reverse cards when importing, instead of the typical front to back cards, as shown in the first example.**

If anyone understands, please let me know! Thank you so much!
![front card](https://user-images.githubusercontent.com/9096662/99702479-d2b2e380-2a63-11eb-8c0e-3f35c5000e0f.PNG)

**Comment by sviatoslav-lebediev** [comment]
Hi, sorry I haven't seen your message. have you found how to do this? Here is a video https://www.youtube.com/watch?v=s2raTx19ByM
you just need to create an additional note type
