### ISSUE TITLE
Says "success! imported *title* but it is not in my decks

### ISSUE THREAD

**Issue by christacuison** [sviatoslav-lebediev/anki-quizlet-importer-extended#182]
Hi,
This is the deck I am trying to import from quizlet: https://quizlet.com/906155391/ins-flash-cards/?funnelUUID=048944e9-c6cd-4109-be2e-3247baede951

Thank you!

**Comment by christacuison** [comment]
I've tried copying and pasting the URL and it did not import.

**Comment by sviatoslav-lebediev** [comment]
Hi, hm I don't know I've tried to import and everything looks ok
Here is your deck 
[INS.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/15186443/INS.apkg.zip)
