### ISSUE TITLE
i keep getting an error when i try to import

### ISSUE THREAD

**Issue by isin06** [sviatoslav-lebediev/anki-quizlet-importer-extended#184]
Every time I try to import this comes up 'Anki encountered a problem. Please follow the troubleshooting steps'
I have followed the troubleshooting steps and used the page html and opened the flashcard html page in incognito mode and I'm still encountering this error.

**Quizlet deck URL**
https://quizlet.com/ie/874786807/hamlet-essential-quotes-flash-cards/?funnelUUID=1f499054-dcd7-40e4-853f-25ded2aa4a4a

**Additional context**
This is the debug information

Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\isinn\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "C:\Users\isinn\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 431, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'FrontText'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T18:55, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T02:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126 1771074083

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
Hi, 99% that you have changed the Basic Quizlet Extended note type
take a look at the 4th item here https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ

**Comment by isin06** [comment]
hi, i changed it back to the Basic Quizlet Extended card and it still not working :(

**Comment by sviatoslav-lebediev** [comment]
so you have removed that note type and you still have this issue ? hm you can try to remove that note type but  i would recommend creating a backup before.
