### ISSUE TITLE
speech sped up 

### ISSUE THREAD

**Issue by sbgmyql** [sviatoslav-lebediev/anki-quizlet-importer-extended#186]
**Describe the bug**
one of the audio files was sped up (only one out of 33 ) around *1.5 faster  
**Quizlet deck URL**
https://quizlet.com/920451302/%D7%94%D7%9B%D7%A0%D7%94-%D7%9C%D7%9E%D7%91%D7%97%D7%9F-%D7%91%D7%A2%D7%A8%D7%91%D7%99%D7%AA-flash-cards/?i=42vs0a&x=1qqt

**Additional context**
i was using a license key 
and the audio was in Arabic

**Comment by sviatoslav-lebediev** [comment]
could you tell me which one ? The add-on actually just downloads the file so I'm not sure that i can fix this

**Comment by sbgmyql** [comment]
i don't remember and  i do not have access to the anki  may be it's a problom in quizlet or data transfer error

**Comment by sviatoslav-lebediev** [comment]
got it
