### ISSUE TITLE
Quizlet import with audio not working

### ISSUE THREAD

**Issue by malotru007** [sviatoslav-lebediev/anki-quizlet-importer-extended#19]
Seen that other people have been having that issue. Used to work but no more. I updated Ank and went to the link that you gave but still with no success. I get the familiar error message:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.38 (355e4cd5) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.14.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-01-10 16:16:05
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "anki/notes.py", line 106, in _fieldOrd
KeyError: 'BackAudio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/junior/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 302, in onCode
    self.createDeck(deck)
  File "/Users/junior/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 358, in createDeck
    note["BackAudio"] = "[sound:" + file_name + "]"
  File "anki/notes.py", line 114, in __setitem__
  File "anki/notes.py", line 108, in _fieldOrd
KeyError: 'BackAudio'

https://quizlet.com/nl/550868544/new-common-words-list-part-4-flash-cards/?funnelUUID=4478e1a5-4686-440f-82fb-e5d7755b31e0

Any help would be appreciated. Thanks!

**Comment by sviatoslav-lebediev** [comment]
Hi, sorry, I haven't seen your message. Does it work right now? I tried your URL and I could import all words.

**Comment by malotru007** [comment]
Hi, Thanks for getting back to me. Yes, still receiving the same error message as above...

**Comment by sviatoslav-lebediev** [comment]
Could you please take a look, maybe you have changed this note type `Basic Quizlet Extended` if so please rename it, restart anki and try import again.
