### ISSUE TITLE
Cannot import set from quizlet

### ISSUE THREAD

**Issue by goldempathy** [sviatoslav-lebediev/anki-quizlet-importer-extended#190]
**Describe the bug**
When trying to import any set from Quizlet, there is an error and the set is not imported

**Quizlet deck URL**
All decks that I tried

**Additional context**
Error given is as follows
```
Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Captcha Challenge…</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16" href="data:ima``` . . .

**Comment by Amanuel800** [comment]
The same issue is happening to me too. I tried troubleshooting, but it still shows me the same thing it is showing [goldempathy](https://github.com/goldempathy).

**Comment by sviatoslav-lebediev** [comment]
hi, i know, cloudflare now blocks requests from the add-on. I need time to fix this.

**Comment by sviatoslav-lebediev** [comment]
for now please use HMTL MODE
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/cd8cbce7-cb77-4695-ad13-b18922f37150)

**Comment by sviatoslav-lebediev** [comment]
I will close this issue because we have the same one here. Please add your questions here if you need https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/189
