### ISSUE TITLE
Error in Quizlet importer 

### ISSUE THREAD

**Issue by Same09ark** [sviatoslav-lebediev/anki-quizlet-importer-extended#193]
**Describe the bug**
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.4-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/saman/Library/Application Support/Anki2/addons21/538351043/__init__.py", line 610, in runQuizletPlugin
  File "/Users/saman/Library/Application Support/Anki2/addons21/538351043/__init__.py", line 186, in __init__
  File "/Users/saman/Library/Application Support/Anki2/addons21/538351043/__init__.py", line 261, in getCookies
TypeError: 'NoneType' object is not subscriptable

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2023-10-21T08:34, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T01:15, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T12:55, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T19:43, 'None', '']
Study Time Stats ['1247171202', 2024-02-24T10:59, 'None', '']
True Retention ['613684242', 2017-11-19T14:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1247171202 1362209126 1374772155 1771074083 613684242 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Quizlet deck URL**

https://quizlet.com/ca/818797062/cpps-304-pharmacokinetics-flash-cards/?i=11kd2h&x=1jqt

**Additional context**

There is an error with importing quizlet flaschcards from Quizlet. I have followed the instructions as much as I can but nothing is working.

**Comment by Vasimat** [comment]
My bug, please help:)


Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 610, in runQuizletPlugin
    __window = QuizletWindow()
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 188, in __init__
    self.initGUI()
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 252, in initGUI
    self.setSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
AttributeError: type object 'QSizePolicy' has no attribute 'Minimum'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Zzz not maintained  may not work Improved Quizlet to Anki 21 Importer ['538351043', 2020-11-15T03:16, 'None', '']

===IDs of active AnkiWeb add-ons===
538351043

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
Guys I guess you use a different plugin :) my plugin is here https://ankiweb.net/shared/info/1362209126
But it looks like you use this one https://ankiweb.net/shared/info/538351043
