### ISSUE TITLE
Quizlet debug 

### ISSUE THREAD

**Issue by Daraniashley3** [sviatoslav-lebediev/anki-quizlet-importer-extended#197]
**Describe the bug**
 Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.3.1-arm64-arm-64bit

Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ashleythammavongsa/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "/Users/ashleythammavongsa/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 431, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'FrontText'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2023-10-21T10:34, 'None', '']
Cloze Anything ['330680661', 2021-12-09T02:34, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T21:19, 'None', mod]
Edit Field During Review Cloze ['385888438', 2024-01-03T02:19, '6.18', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T07:47, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Progress bar - Visualize reviewed cards and remaining Fixed by Shige ['1708250053', 2024-08-14T13:28, 'None', mod]
Puppy Reinforcement ['1722658993', 2023-11-16T07:59, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T13:55, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1210908941 1362209126 1374772155 1708250053 1722658993 1771074083 330680661 385888438 46611790 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Quizlet deck URL**

https://quizlet.com/939991011/csp-chapter-33-flash-cards/?funnelUUID=a98c4b3f-bca3-4faf-9c5f-f60a44abee02

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Hi, please take a look at https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ
4th item
