### ISSUE TITLE
Quizlet Debug

### ISSUE THREAD

**Issue by khauzy** [sviatoslav-lebediev/anki-quizlet-importer-extended#199]
**Describe the bug**
Anki encountered a problem. Please follow the troubleshooting steps.

Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

(Imported 9 other decks previously just fine, suddenly I cannot do any new ones)

**Quizlet deck URL**

(https://quizlet.com/942140689/beginner-thai-chapter-8-flash-cards/?i=5pdfq&x=1jqt)

**Additional context**Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-arm64-arm-64bit

Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jay/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "/Users/jay/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 431, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'FrontText'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
HyperTTS - Add speech to your flashcards ['111623432', 2024-09-11T18:46, 'None', mod]
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T13:55, 'None', '']
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-17T14:28, 'None', '']

===IDs of active AnkiWeb add-ons===
111623432 1362209126 864545277

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by khauzy** [comment]
Nevermind, changing the text back seems to have resolved it, even though it worked fine for previous cards.

**Comment by sviatoslav-lebediev** [comment]
ok, but i guess this is the same issue https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/197
