### ISSUE TITLE
Can't find a deck with ID 8

### ISSUE THREAD

**Issue by tedblizzard** [sviatoslav-lebediev/anki-quizlet-importer-extended#2]
Love this addon but currently getting this error:  Can't find a deck with ID 8
https://quizlet.com/_8kngku?x=1jqt&i=7fb0s

![image](https://user-images.githubusercontent.com/2208182/89856729-4c654680-dbc4-11ea-8531-0e6662b628be.png)

**Comment by sviatoslav-lebediev** [comment]
@tedblizzard I've tried to open this URL but it looks like it's protected. But Quizlet actually redirected me to this one https://quizlet.com/518416302/flash-cards/ . Could you please check if this URL is correct and try to use this one instead of https://quizlet.com/_8kngku?x=1jqt&i=7fb0s

**Comment by tedblizzard** [comment]
My apologies.  You are correct.  Thank you so much for your help and this app.

**Comment by sviatoslav-lebediev** [comment]
sure, np
