### ISSUE TITLE
Quizlet Public Deck Mistaken as Private

### ISSUE THREAD

**Issue by ashley100perfection** [sviatoslav-lebediev/anki-quizlet-importer-extended#200]
**Describe the bug**
My public Quizlet Deck is mistaken as private and can not be imported

**Quizlet deck URL**
https://quizlet.com/942266423/aerobic-gram-negative-bacilli-gnb-1-flash-cards/

**Additional context**
Error from the addon window
<img width="717" alt="Screenshot 2024-09-14 at 3 04 01 PM" src="https://github.com/user-attachments/assets/9c109a15-295f-4d6f-86ba-77007e41148e">

**Comment by sviatoslav-lebediev** [comment]
Hi, I've tried, and I could import this deck. `Sorry, this is a private deck :(` we can show when we receive a 403 error from the quizlet. So I would try to switch to another wifi network if it's possible, or you can always use the HTML mode, The video is here https://vimeo.com/830860191

[Aerobic gram negative bacilli (GNB) 1.apkg.zip](https://github.com/user-attachments/files/17002908/Aerobic.gram.negative.bacilli.GNB.1.apkg.zip)

**Comment by ashley100perfection** [comment]
> Hi, I've tried, and I could import this deck. `Sorry, this is a private deck :(` we can show when we receive a 403 error from the quizlet. So I would try to switch to another wifi network if it's possible, or you can always use the HTML mode, The video is here https://vimeo.com/830860191
> 
> [Aerobic gram negative bacilli (GNB) 1.apkg.zip](https://github.com/user-attachments/files/17002908/Aerobic.gram.negative.bacilli.GNB.1.apkg.zip)

Thank you so much! It worked after I used a VPN!
