### ISSUE TITLE
Keeps importing random quizlet deck

### ISSUE THREAD

**Issue by samvds9** [sviatoslav-lebediev/anki-quizlet-importer-extended#201]
I am trying to import a quizlet deck from a class I am a part of in quizlet but every time I try it imports a random deck of 100 SAT words which is nothing to do with what I'm trying to import.

**Comment by sviatoslav-lebediev** [comment]
Could you share your deck url ? This information is not enough to help you.

**Comment by sviatoslav-lebediev** [comment]
going to close, please create a new issue and add more info
