### ISSUE TITLE
throwing exception 403 AFTER using HTML

### ISSUE THREAD

**Issue by verists** [sviatoslav-lebediev/anki-quizlet-importer-extended#203]
it imports up to 10 cards before the message 'throwing exception 403' appears.

the deck in question (not made by me): https://quizlet.com/th/259370199/hsk-4-flash-cards
the problem works with other flashcard links of the same topic e.g. https://quizlet.com/249010277/flashcards

please see the attached image. thanks!

<img width="600" alt="image" src="https://github.com/user-attachments/assets/a7e3719f-7802-42a6-aff1-ee4db2986abc">

**Comment by sviatoslav-lebediev** [comment]
Hi, have you checked `Skip errors` ?
![image](https://github.com/user-attachments/assets/6026d896-3e4c-479d-a947-3ca04a12d033)

**Comment by verists** [comment]
YOU. ARE. A. LIFESAVER. THANK YOU SO MUCH!!!!!!!!!

**Comment by sviatoslav-lebediev** [comment]
the only issue is that with this checkbox it can skip some images or audio. just want you to know
