### ISSUE TITLE
Importing some random deck instead of mine

### ISSUE THREAD

**Issue by samvds9** [sviatoslav-lebediev/anki-quizlet-importer-extended#209]
I am trying to import a quizlet deck from a class I am a part of in quizlet but every time I try it imports a random deck of 100 SAT words which is nothing to do with what I'm trying to import. The URL is (https://quizlet.com/user/dylan_rosaa/folders/402-hivgumidmicro). I get that this is a folder of lots of decks of flashcards but is there a way of me importing the whole folder at once as otherwise it will take me forever to import them? Thanks

**Comment by sviatoslav-lebediev** [comment]
Hi, there is no way to import folders; we even have a feature request for this: https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/167, but to be honest, I don't have enough time to implement it.

As for the second problem - could you send me a deck url ? I've tried to import 1 deck from your set https://quizlet.com/gb/782474654/hyposplenism-flash-cards/?funnelUUID=97f124ac-8675-4af1-ae04-c68196d00536 and I don't see any issues.
![image](https://github.com/user-attachments/assets/ead5ead0-ee08-4e2b-be4c-b7bd46cae913)
![image](https://github.com/user-attachments/assets/cb25a0d2-e949-4c10-82e8-dd80da74276c)

**Comment by samvds9** [comment]
There is no second issue this error was only occurring when I tried to import the whole folder, it works fine when I just try and import the decks individually. I was just hoping you might be able to import the whole folder at once to save time. Thanks for your help.

**Comment by sviatoslav-lebediev** [comment]
Got it, yes, as I said, we don't have this feature yet :( 
You are welcome.
