### ISSUE TITLE
 Add-ons possibly involved: ⁨Zzz not working Improved Quizlet to Anki 21 Importer⁩

### ISSUE THREAD

**Issue by BarbieQ4U** [sviatoslav-lebediev/anki-quizlet-importer-extended#211]
**Describe the bug**
It is not allowing me to import from Quizlet.

**Quizlet deck URL** 
https://quizlet.com/944344535/microbial-genetics-bacterial-dna-and-mutations-flash-cards/?funnelUUID=838a3a21-d255-43b2-a629-53b48c2f0886

**Comment by sviatoslav-lebediev** [comment]
Hi, I need more details, what error did you receive ? I've tried to import your deck and didn't see any issues

![image](https://github.com/user-attachments/assets/e281f541-2bea-48bc-9c98-b847c5d0a196)

here is your deck
[Microbial Genetics_ Bacterial DNA and Mutations.apkg.zip](https://github.com/user-attachments/files/17465040/Microbial.Genetics_.Bacterial.DNA.and.Mutations.apkg.zip)

**Comment by BarbieQ4U** [comment]
Hi! Thank you for responding. Every time I click on import from Quizlet it says this:
Add-ons possibly involved: ⁨Zzz not working Improved Quizlet to Anki 21 Importer⁩

**Comment by BarbieQ4U** [comment]
Hi! the add-on is right I just used the wrong code for the add-on. Lol sorry!

**Comment by sviatoslav-lebediev** [comment]
oh, yep, sometimes this happens, people use the old add-on and ping me that something is wrong with mine :)
no worries, happy that you found the problem
