### ISSUE TITLE
No luck, tried everything

### ISSUE THREAD

**Issue by maryvnd1** [sviatoslav-lebediev/anki-quizlet-importer-extended#213]
**Describe the bug**
I get errors when I try to import any set. Tried restarting the app, updating/reinstalling the app/addon, pasting HTML, etc. What I get is an empty deck.

**Quizlet deck URL** 
https://quizlet.com/957731834/on-screen-c1-module-7-flash-cards/

**Additional context**
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.6.1-arm64-arm-64bit

Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mariabaglay/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 385, in onCode
    self.createDeck(deck)
  File "/Users/mariabaglay/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 432, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'FrontText'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-10-10T21:19, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T04:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126 1771074083

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
Hi, I guess you haven't tried everything :) At least you haven't read this https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ
4th item

**Comment by maryvnd1** [comment]
It's working!!! Tysm
