### ISSUE TITLE
error message when importing, "Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by dogpipolodog** [sviatoslav-lebediev/anki-quizlet-importer-extended#216]
Hello! 

I have been having issues with the add-on. It used to work, but now I systematically get the error message "Expecting value: line 1 column 1 (char 0)".

I have tried with many different quizlet links, ex. https://quizlet.com/fr-fr/fiches-de-memorisation/cm1-museologie-722984622

I have tried:
- using html, but quizlet can't find it back
- using a vpn
- deleting and downloading the add-on again
- incognito mode
- turning off my adblock

If you have any idea with what's going on, I'd be super grateful! It had been working wonderfully so far.

Thank a bunch

Leïla

**Comment by sviatoslav-lebediev** [comment]
Hi, could you please send me the whole error ?

**Comment by sviatoslav-lebediev** [comment]
I've tried to use the HTML mode and i could import your deck
But it looks like your url has a different format than my add-on support, so I guess you need to use the HTML mode all the time
[CM1 MUSEOLOGIE.apkg.zip](https://github.com/user-attachments/files/17643830/CM1.MUSEOLOGIE.apkg.zip)

**Comment by dogpipolodog** [comment]
Hello! Thank you so much for your quick response. I finally got it : by changing the format of the url, from https://quizlet.com/fr-fr/fiches-de-memorisation/cm1-museologie-722984622 to https://quizlet.com/722984622/cm1-museologie-flash-cards/ it works perfectly well. 
thank you for your add-on, its rly so helpful!! :))
have a great day
