### ISSUE TITLE
Audio being chopped

### ISSUE THREAD

**Issue by WillPowerJA** [sviatoslav-lebediev/anki-quizlet-importer-extended#22]
Hello, the addon seems to work pretty well. The only small issue I have at the moment is that the audio I've imported gets chopped off at the end. For example, take the Spanish word "Gracias." The card will only say, "Gracia," leaving out the last "s" sound. Similar things happen with more complex cards. Any fix? Otherwise the addon works great.

Quizlet URL: https://quizlet.com/522126042/spanish-ia-8-week-semana-1-bienvenidos-flash-cards/

By the way, I'm using Anki v.2.1.35

**Comment by WillPowerJA** [comment]
By the way, I'm on Anki v.2.1.35

**Comment by sviatoslav-lebediev** [comment]
thx, I will take a look

**Comment by sviatoslav-lebediev** [comment]
Do you still have this problem? I've tried to download your Quizlet and don't see any problems. Here is a a link to exproted items https://filebin.net/md0dgifkt257kslx/Spanish_I_A____8_Week___Semana_1____Bienvenidos_.apkg?t=a0qjx6vz

**Comment by WillPowerJA** [comment]
> 
> 
> Do you still have this problem? I've tried to download your Quizlet and don't see any problems. Here is a a link to exproted items https://filebin.net/md0dgifkt257kslx/Spanish_I_A____8_Week___Semana_1____Bienvenidos_.apkg?t=a0qjx6vz

Hi @sviatoslav-lebediev, I do still have the problem unfortunately. The strange thing is, it even happens with the exported deck you attached. So that makes me wonder if it's something wrong on my end? Even stranger though is the problem occurs whether or not I'm on PC or iPhone mobile Anki. It's as if the audio on every card is cut 0.5 seconds short. For example, find the card "No entiendo" in that deck. For me, the audio says, "No entien" rather than "No entiendo". It cuts short just barely before the end.

**Comment by sviatoslav-lebediev** [comment]
Hi, honestly, I don't know how to help you with your desktop, but I would try to reinstall the audio drivers
