### ISSUE TITLE
Reverse card

### ISSUE THREAD

**Issue by AleksisME** [sviatoslav-lebediev/anki-quizlet-importer-extended#23]
Добрый день, почему при импорте автоматически не создаются обратные карточки? М.б. можно добавить такую опцию?

**Comment by WillPowerJA** [comment]
Hello. I'm not the developer of the addon, but I did figure out how to add reverse cards. Watch this video around 2:40: https://www.youtube.com/watch?v=s2raTx19ByM. You type a "Y" in the "Add Reverse" field on the card. You can do this for each individual card. Or, as I did, you can download the "Batch edit" Anki addon (https://ankiweb.net/shared/info/291119185) and do this all at once. Hope this helps.

**Comment by sviatoslav-lebediev** [comment]
Hi, thank you @WillPowerJA, yes we have the same issue here https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/18, and I've mentioned the same video :)
