### ISSUE TITLE
Set add reverse from config or import window

### ISSUE THREAD

**Issue by AlexLloyd0** [sviatoslav-lebediev/anki-quizlet-importer-extended#29]
I'd always like import to create reversed cards. It would be great if there were an easier way to do this.

Either in the config file or a checkbox in the import window would be great.

My current workflow is:

1. Import deck
2. Browse -> select the new deck
3. Select all cards
4. Right click -> Notes -> Find and Replace
5. Replace "" with "true" in the Add Reverse field

Which is quite slow and error prone (maybe there's already a better way of doing things)

**Comment by AlexLloyd0** [comment]
I'm happy to implement this (*) if you confirm that there's no easier way to do this in the existing extension?


(*) I have no experience developing Anki add-ons so I would be slow at implementing this simple feature

**Comment by sviatoslav-lebediev** [comment]
Hi @AlexLloyd0, sorry didn't see your message :( 
you can try to add a new line here https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/blob/4121da52c9f7c433976c3a011f106632fae61263/__init__.py#L341 
something like this `note["Add Reverse"] = True` or `note["Add Reverse"] = "true"`
you can open a folder with the installed plugin and change it there, restart Anki and try to import decks. if it works we will add it as an option.

![image](https://user-images.githubusercontent.com/19693768/160284671-cd5e96c3-a7a2-40ef-b120-fc79df5e06be.png)

**Comment by sviatoslav-lebediev** [comment]
@AlexLloyd0  I will add this as a checkbox

**Comment by sviatoslav-lebediev** [comment]
done
