### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by GovindenJerome** [sviatoslav-lebediev/anki-quizlet-importer-extended#3]
Hi, 

I get an error while trying to import this deck : https://quizlet.com/mx/488376244/sicher-b2-lektion-1-flash-cards/ using Anki 2.1.23.

Could you check it out?

**Comment by sviatoslav-lebediev** [comment]
Hi, sure, will take a look

**Comment by sviatoslav-lebediev** [comment]
I've updated this addon, could you please take a look if it works? I've successfully imported your deck. I'm going to close this issue. Please reopen it if you still have a problem with it

**Comment by sviatoslav-lebediev** [comment]
sure, np
