### ISSUE TITLE
Add-On is not downloading the original audio and instead only the Text to Speech audio

### ISSUE THREAD

**Issue by proelf98** [sviatoslav-lebediev/anki-quizlet-importer-extended#31]
I want to have the original audio from the Quizlet deck but only get the text to speech audio. (I am using the latest version from today 4/17/2022)

Any solution?

**Comment by sviatoslav-lebediev** [comment]
Hi, could u please send me a deck? and a list of phrases where you have the original audio

**Comment by rkstedman** [comment]
I'm also running into this issue - here's a link to my deck: https://quizlet.com/460625273/level-7-lesson-1-flash-cards/
The FrontText, FrontAudio, and BackText import correctly but the BackAudio is missing. Would appreciate any help you can provide.

**Comment by sviatoslav-lebediev** [comment]
should work. Try to update a version of the addon

**Comment by proelf98** [comment]
Thank you very much <3 it works now. Do you have a digital tipping jar or sth.?

**Comment by rkstedman** [comment]
+1 It works for me too! Thank you - would love to know your digital tipping jar as well :)

**Comment by sviatoslav-lebediev** [comment]
nope, I don't have a tipping jar :) don't worry, enjoy studying. if you need any additional features, let me know
