### ISSUE TITLE
Issue with importing Quizlet to Anki

### ISSUE THREAD

**Issue by biggiebuns** [sviatoslav-lebediev/anki-quizlet-importer-extended#36]
Error: "Can't find a deck with the ID 3"   when trying to import any Quizlet decks.

Quizlet link:
https://quizlet.com/_a3s5bf?x=1jqt&i=lxb7j

**Comment by sviatoslav-lebediev** [comment]
Hi, could u try to import the full URL instead https://quizlet.com/611013867/basic-sciences-ii-week-2-material-flash-cards/?x=1jqt ?
