### ISSUE TITLE
Partial Deck Import

### ISSUE THREAD

**Issue by RitaSayre** [sviatoslav-lebediev/anki-quizlet-importer-extended#38]
Hi, when I import from Quizlet, I only get a max of 20 cards. When importing, I see a message that it successfully imported the entire deck (36 cards, 65 cards, etc), but only 20 appear and are listed.  I am using a mac with Anki Version ⁨2.1.54. Thanks!

**Comment by sviatoslav-lebediev** [comment]
hi, could you give me that Quizlet deck link ?

**Comment by mhujer** [comment]
@RitaSayre my guess is that the deck was imported successfully, but the Anki displays that there are just 20 new cards for today.

Try using the "Browse" button in the Anki to see the imported cards.
