### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by sviatoslav-lebediev** [sviatoslav-lebediev/anki-quizlet-importer-extended#39]
hello, my computer is windows and I actually use a vpn, BUT still cannot import cards success. I can only function with quizlet-importer-v1.1.1-captcha

here is my description:

Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-17 15:28:24

Caught exception:
Traceback (most recent call last):
File "urllib3.connectionpool", line 700, in urlopen
File "urllib3.connectionpool", line 994, in _prepare_proxy
File "urllib3.connection", line 364, in connect
File "urllib3.connection", line 499, in _connect_tls_proxy
File "urllib3.util.ssl_", line 453, in ssl_wrap_socket
File "urllib3.util.ssl_", line 495, in _ssl_wrap_socket_impl
File "ssl", line 500, in wrap_socket
File "ssl", line 1040, in _create
File "ssl", line 1309, in do_handshake
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests.adapters", line 440, in send
File "urllib3.connectionpool", line 785, in urlopen
File "urllib3.util.retry", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='quizlet.com', port=443): Max retries exceeded with url: /190060929/flashcards (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\songz\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 472, in run
r = requests.get(self.url, verify=False, headers=headers, cookies=cookies)
File "requests.api", line 75, in get
File "requests.api", line 61, in request
File "requests.sessions", line 529, in request
File "requests.sessions", line 645, in send
File "requests.adapters", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='quizlet.com', port=443): Max retries exceeded with url: /190060929/flashcards (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\songz\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 523, in run
self.errorMessage = "{}\n-----------------\n{}".format(e, r.text)
AttributeError: 'NoneType' object has no attribute 'text'

would you mind help me?

————————————————————————————————————
quizlet link：https://quizlet.com/190060929/ch01german-for-reading-flash-cards/

when I try without VPN, it shows: Sorry, it's behind a captcha, try to disable VPN.

note: I come from China. Would it influence?

**Comment by Songztu** [comment]
Thank very much to you since you take your time to solve this issue. 
Hope it will not spend too much time. 
Sincere gratitude.

**Comment by sviatoslav-lebediev** [comment]
I will try to add an ability to copy/paste HTML from the quizlet.com. in this case, the addon will use that HTML instead of downloading it.  Hope I will have time tomorrow

**Comment by sviatoslav-lebediev** [comment]
@Songztu Hi, could you please try to check if this approach works for you.
1. Open Anki. Click Tools/Add-ons
2. Select Quizlet to Anki 21 Importer...
3. Click View Files
4. Open __init__.py in an editor
5. Replace content of __init__.py using this text code https://raw.githubusercontent.com/sviatoslav-lebediev/anki-quizlet-importer-extended/eb53ce4b61131ec0634fd2dadaa4c15e9399aaf4/__init__.py
6. Restart Anki
7. Your link is https://quizlet.com/190060929/ch01german-for-reading-flash-cards/ . `190060929` is the id of the deck. Try to open this URL https://quizlet.com/190060929/flashcards in your browser. 
8. Right click on the https://quizlet.com/190060929/flashcards page and select `Inspect`. It will open DevTools.
9. Right click on the HTML tag and select Copy outerHTML
10. Paste that HTML to the addon field and enter the URL
11. Try to import.


I understand that this is a more complicated approach, but I want to check if it works for you.  If it works maybe we will try to simplify it somehow. I don't want to try to solve your issue with proxy because I can take a lot of time and I don't know even how to test it.

![image](https://user-images.githubusercontent.com/19693768/197404683-e34935b1-5edb-4d75-8dd2-f718180767fd.png)
![image](https://user-images.githubusercontent.com/19693768/197404862-e5558c30-7866-4520-84c6-fcbb18940a30.png)
![image](https://user-images.githubusercontent.com/19693768/197404902-30d8ae90-4a00-494d-b659-70070e423fe4.png)

**Comment by sviatoslav-lebediev** [comment]
I've updated a version of the addon, please try one more time. If you still have a problem, please create another issue.

**Comment by Songztu** [comment]
I've tried but failed. so sad.

anki report: 'NoneType' object has no attribute 'group'
![#39](https://user-images.githubusercontent.com/116066422/204528971-cbfd4d8f-5b81-4176-a076-8f6a58f5ac27.jpg)

**Comment by sviatoslav-lebediev** [comment]
could u p

**Comment by Songztu** [comment]
I'm sorry for not replying so many days. I just took a open surgery.

I tried the method you proposed in Oct. 24, still unsolved. 
Because the whole text is too long to comment, here is the whole text:
[https://shimo.im/docs/Ee32MlWQnjHBPoA2]

<img width="695" alt="#39(2)" src="https://user-images.githubusercontent.com/116066422/208290968-1ab215e9-dc68-4e8c-aec7-be668b743838.png">

Besides, i don't know how to set a prop.

Thank you very much for spending much time to help me, wish you all well.

**Comment by sviatoslav-lebediev** [comment]
What vpn do you use and what country do you choose ?

**Comment by Songztu** [comment]
I use clash for windows as vpn, and choose Singapore, Japan or America, they all failed.

**Comment by sviatoslav-lebediev** [comment]
:( I can't reproduce this behavior. and you always receive `Sorry, it's behind a captcha, try to disable VPN.`, right? Can you remove this plugin and install it one more time?

**Comment by Songztu** [comment]
I re-install the add-on, still doesn't work. I can only import the cards with this version _quizlet-importer-v1.1.1-captcha_ but without audio.

**Comment by sviatoslav-lebediev** [comment]
could you provide a link for `quizlet-importer-v1.1.1-captcha` ? maybe i can take some code from that plugin

**Comment by Songztu** [comment]
here:
[https://github.com/kelciour/improved-quizlet-to-anki-21-importer/releases/tag/v1.1.0-captcha](url)

**Comment by sviatoslav-lebediev** [comment]
not we are different :) i will take a look and will let you know
