### ISSUE TITLE
error importing deck

### ISSUE THREAD

**Issue by mmthomas312** [sviatoslav-lebediev/anki-quizlet-importer-extended#4]
I put in the link to import and then the below message pops up.  It won't let me import the deck

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.5
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-02 11:43:15
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/maggie/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 264, in onCode
    self.createDeck(deck)
  File "/Users/maggie/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 291, in createDeck
    terms = result['terms']
KeyError: 'terms'

**Comment by sviatoslav-lebediev** [comment]
Hi, could you please provide a link to the deck? you have clicked on the `Import Deck` button, right ?

**Comment by vincentianxing** [comment]
Got the exact same error with this deck link: https://quizlet.com/25860132/genki-lesson-1-vocabulary-p-40-flash-cards/

Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.5
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-01 19:51:02
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/zhutianxing/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 264, in onCode
    self.createDeck(deck)
  File "/Users/zhutianxing/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 291, in createDeck
    terms = result['terms']
KeyError: 'terms'

**Comment by vincentianxing** [comment]
> Got the exact same error with this deck link: https://quizlet.com/25860132/genki-lesson-1-vocabulary-p-40-flash-cards/
> 
> Debug info:
> Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
> Platform: Mac 10.15.5
> Flags: frz=True ao=True sv=1
> Add-ons, last update check: 2020-09-01 19:51:02
> Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩
> 
> Caught exception:
> Traceback (most recent call last):
> File "/Users/zhutianxing/Library/Application Support/Anki2/addons21/1362209126/**init**.py", line 264, in onCode
> self.createDeck(deck)
> File "/Users/zhutianxing/Library/Application Support/Anki2/addons21/1362209126/**init**.py", line 291, in createDeck
> terms = result['terms']
> KeyError: 'terms'

With all other add-ons turned off.

**Comment by sviatoslav-lebediev** [comment]
yep, I see this error as well. will take a look, thx

**Comment by sviatoslav-lebediev** [comment]
It looks like the original plugin has the same issue
https://ankiweb.net/shared/info/538351043

**Comment by sviatoslav-lebediev** [comment]
it seems to me that Quizlet has changed their site, that's why we need to change our code.

**Comment by mmthomas312** [comment]
Yep I pressed import deck! It was this link https://quizlet.com/522168126/mcgraw-hill-connect-spanish-chapter-1-flash-cards/

**Comment by tweinstein18** [comment]
Hello I have been having the exact same problem trying to use this link. Any advice? https://quizlet.com/81925348/creencias-e-ideologias-vocabulario-flash-cards/

**Comment by sviatoslav-lebediev** [comment]
@tweinstein18 right now we can't import any decks because quizlet has changed their site. we need to rewrite a parsing part from the scratch

**Comment by sviatoslav-lebediev** [comment]
I've fixed the issue, please update a version of the addon and try to import sets
