### ISSUE TITLE
Add on saying cant find the deck with id 4

### ISSUE THREAD

**Issue by Lray2** [sviatoslav-lebediev/anki-quizlet-importer-extended#40]
https://quizlet.com/_c4vyts?x=1jqt&i=2ufy8
keeps saying what I wrote above :(. None of the decks I have tried work

**Comment by sviatoslav-lebediev** [comment]
The addon doesn't support short URLs, it needs to know an id of the deck. Try to open your URL in a browser and use the full URL. For example your ^ URL should be https://quizlet.com/733804048/psych-344-exam-2-book-chapters-5678-flash-cards/?x=1jqt

**Comment by Lray2** [comment]
that worked thank you so much!
