### ISSUE TITLE
import quizlet not working 

### ISSUE THREAD

**Issue by molassescookies** [sviatoslav-lebediev/anki-quizlet-importer-extended#42]
quizlet link: https://quizlet.com/738298002/im-eor-pulmonology-flash-cards/

when i try to import my quizlet, it says the add on is causing a bug problem and gives me error message

**Comment by sviatoslav-lebediev** [comment]
Hi, could you provide the whole error text ?

**Comment by AP32OVO** [comment]
i also get an error message that states 
"'NoneType' object has no attribute 'group'
-----------------"

and a bunch of other really long text

**Comment by sviatoslav-lebediev** [comment]
@AP32OVO could you provide the deck URL please ?

**Comment by AP32OVO** [comment]
It doesn't matter which one of the decks its all the same but here are two of them.

https://quizlet.com/703265462/pcat-chapter-1-laboratory-flash-cards/
or
https://quizlet.com/ca/604138385/animal-phyla-non-chordates-flash-cards/

**Comment by sviatoslav-lebediev** [comment]
thx, i will take a look, maybe quizlet has changed something

**Comment by sviatoslav-lebediev** [comment]
hm, I've re-installed the addon and tried to import your decks, and it works. `"'NoneType' object has no attribute 'group'` means that the addon can't find the required data in the HTML, so maybe for some reason on your computer, it can't fetch the correct HTML. 

Could you try to check this approach ? also please provide the whole error text it can help to debug the problem.
https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/39#issuecomment-1288153471

**Comment by sviatoslav-lebediev** [comment]
I've updated a version of the addon, please try one more time. If you still have a problem, please create another issue.
