### ISSUE TITLE
Issue october 28th

### ISSUE THREAD

**Issue by AP32OVO** [sviatoslav-lebediev/anki-quizlet-importer-extended#43]
After doing inspect and follwing the steps with HTML i get an error that states:

'NoneType' object has no attribute 'group'
-----------------

**Comment by sviatoslav-lebediev** [comment]
https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/42#issuecomment-1295801888

**Comment by sviatoslav-lebediev** [comment]
@AP32OVO i've released a new version of the addon, try to update and check if it works for you
