### ISSUE TITLE
How to donate to your Ko-Fi

### ISSUE THREAD

**Issue by hgy7756** [sviatoslav-lebediev/anki-quizlet-importer-extended#44]
I just tried to donate to your Ko-Fi page using PayPal, and it denied me saying something about "international regulation/standards" or something like that. Any idea why that would happen?

**Comment by sviatoslav-lebediev** [comment]
Hi, thank you for letting me know. Maybe it's because I'm Ukrainian. I will take a look.

**Comment by sviatoslav-lebediev** [comment]
going to close this issue, I've switched to the https://www.buymeacoffee.com/moro.programmer . Thank you again for letting me know.
