### ISSUE TITLE
Anki to Quizlet importer not functioning

### ISSUE THREAD

**Issue by watrmelone** [sviatoslav-lebediev/anki-quizlet-importer-extended#47]
{"statusCode":500,"code":"ERR_NON_2XX_3XX_RESPONSE","error":"Internal Server Error","message":"Response code 403 (Forbidden)"}

Tried a few different decks, still didn't work. Also used a vpn, still didn't work. Not quite sure what to do

**Comment by sviatoslav-lebediev** [comment]
Hi, could you provide a deck url ?
