### ISSUE TITLE
error when uploading sets from quizlet

### ISSUE THREAD

**Issue by henrylane5** [sviatoslav-lebediev/anki-quizlet-importer-extended#48]
{"statusCode":500,"code":"ERR_NON_2XX_3XX_RESPONSE","error":"Internal Server Error","message":"Response code 403 (Forbidden)"}

https://quizlet.com/723127502/chapters-1-3-flash-cards/

**Comment by sviatoslav-lebediev** [comment]
Hi, i will take a look

**Comment by sviatoslav-lebediev** [comment]
I've tried to import your url and it looks like everything is ok. 
Could you please  try to do it again ? Maybe you had a network issue? Try to use some VPN + try to add cookies

"""
To download your own private or password-protected sets, go to Tools - Add-ons - Improved Quizlet ... - Config and either set "cookies" or "qlts" and click OK.
To set "cookies", open Chrome DevTools, click the Network tab, reload the page or press Ctrl+R, click on the first request and copy "cookies" value from the request headers.
To set "qlts", open Chrome DevTools, click the Application tab, and copy "qlts" value from the Cookies pane - https://developers.google.com/web/tools/chrome-devtools/storage/cookies.
If "qlts" is set, it takes precedence over "cookies". Once it's done it should be possible to download private or password-protected sets for a limited period of time without making them public.
"""


Here is a screenshot
![image](https://user-images.githubusercontent.com/19693768/205453975-9f3ccef5-514d-4864-8003-fab45e902d23.png)
