### ISSUE TITLE
Issues when importing the deck

### ISSUE THREAD

**Issue by LIU593** [sviatoslav-lebediev/anki-quizlet-importer-extended#49]
**Describe the bug**
After I clicked import deck, this message popped out: {"statusCode":500,"code":"ERR_NON_2XX_3XX_RESPONSE","error":"Internal Server Error","message":"Response code 403 (Forbidden)"}
I tried many times with VPN and without VPN, the results are the same.
**Quizlet deck URL**
https://quizlet.com/it/598470498/the-elves-and-the-shoemaker-flash-cards/
**Additional context**

**Comment by LIU593** [comment]
Thank you for you time!

**Comment by sviatoslav-lebediev** [comment]
will take a look

**Comment by sviatoslav-lebediev** [comment]
+ take a look at the last comment maybe i can help you https://ankiweb.net/shared/info/1362209126
