### ISSUE TITLE
Cannot import any sets as the importer constantly says its private

### ISSUE THREAD

**Issue by ash8918** [sviatoslav-lebediev/anki-quizlet-importer-extended#50]
**Describe the bug**
Hi I really like your quizlet to anki importer its super helpful i was able to import one single set with it however after I tried to import more sets I ran into this issue where basically whatever quizlet set i try to import it will say sorry set is private even though its not password protected at all and completely available to all.

**Quizlet deck URL**
https://quizlet.com/gb/746737627/group-2-a-level-chemistry-flash-cards/
https://quizlet.com/gb/761111185/acids-for-anki-flash-cards/

**Additional context**
Error from the addon window

**Comment by naradashen** [comment]
So this is visible to anyone even though you set that as private

**Comment by ash8918** [comment]
It's really weird but basically the importer does not work at all for me because no matter what set I try like literally any set whatsoever it will say the set is private any set I would try

**Comment by naradashen** [comment]
Its weird can you send a video file. I think that would be helpful. Attach a drive link or a youtube link. Video needs to be clear. Every issue must be included

**Comment by GlitchSlayed** [comment]
Having the same exact issue, my sets are public, but it says they are private

**Comment by sviatoslav-lebediev** [comment]
Hi, thank you for creating this issue, sorry I haven't seen it earlier. 99% of these plugin errors are related to some network issues. Try to use a VPN + try different VPN countries.   
p.s I've tried importing these 2 decks and haven't had any issues.

**Comment by m2zoo4u** [comment]
I am in the US, and the link I can't import is: https://quizlet.com/775825978/absa-study-guide-220-flash-cards/
It says it is private though it is mine and I am logged in. Not sure how to make public...

I am using anki Version ⁨2.1.54 (b6a7760c)⁩
Thanks very much!

**Comment by sviatoslav-lebediev** [comment]
> 

@m2zoo4u I have the same version - ⁨2.1.54 (b6a7760c)⁩ and I can download the deck that you have provided. 
Could you pls take a look if you have any values here ?
![image](https://user-images.githubusercontent.com/19693768/220145222-bff6d4ba-707a-4385-af2a-f07e00388686.png)

**Comment by m2zoo4u** [comment]
Weird. Thanks for the speedy reply! Yes, my config says the same...

**Comment by m2zoo4u** [comment]
{"statusCode":500,"code":"ERR_NON_2XX_3XX_RESPONSE","error":"Internal Server Error","message":"Response code 403 (Forbidden)"} is the error

**Comment by sviatoslav-lebediev** [comment]
I see, it means that the addon could not fetch data directly and tried to use my "proxy server" and failed again
Have you tried to import another deck?

**Comment by m2zoo4u** [comment]
Yes, 1 other, it has the same error.

**Comment by sviatoslav-lebediev** [comment]
hm, weird. i will try to take a look in a few days, maybe i will add some logs that will help us to clarify the problem. Will let you know

**Comment by sviatoslav-lebediev** [comment]
I'm about to finish a proxy service that will help you to download decks. will let you know when it's ready

**Comment by TheCloudCrafter** [comment]
@sviatoslav-lebediev Thank you for your time on this addon.
I have the same issue posted here.
`{"statusCode":500,"code":"ERR_NON_2XX_3XX_RESPONSE","error":"Internal Server Error","message":"Response code 403 (Forbidden)"}`

I'm from the USA on a major ISP. The whole "use USA VPN" solution shouldn't be required in my use case.

**Comment by sviatoslav-lebediev** [comment]
@TheCloudCrafter I've updated the proxy service, could you try to import decks again ?
