### ISSUE TITLE
Adds reverse without promting and cant delete them without it deleting the same card but non reverse

### ISSUE THREAD

**Issue by lexxakw** [sviatoslav-lebediev/anki-quizlet-importer-extended#52]
Hi, I really love the add-on, but while importing from quizlet it automatically adds a reverse card to almost every card I download. This is without checking the add reverse box. I also can't delete the reverse as they also delete the non reverse card so I end up deleting all the cards unintentionally. I also tried importing by clicking on the add reverse box and received an error message, ill paste it in the bottom. This happened to multiple decks but I'm adding an URL to only one and the one the error message belongs to.

**Quizlet deck URL**
https://quizlet.com/241173154/bakteriegenetik-flash-cards/

**Additional context**
Error from the addon window
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 13.2
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-01-31 12:27:52
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'Add Reverse'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alexandrawikstrom/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 318, in onCode
    self.createDeck(deck)
  File "/Users/alexandrawikstrom/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 388, in createDeck
    note["Add Reverse"] = "True"
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'Add Reverse'

**Comment by sviatoslav-lebediev** [comment]
hi, I will take a look, thank you for adding this issue

**Comment by sviatoslav-lebediev** [comment]
I have a question, have you edited this node type `Basic Quizlet Extended`?
You should not edit this note type because the addon uses it. I would recommend you remove this note type and try to import one more time (the addon will re-create it).   I've tried to import your deck and it works in both cases.
p.s. make a backup of your anki before doing any changes :)


![image](https://user-images.githubusercontent.com/19693768/216121141-c143ef6f-784d-4df0-9a20-a41859508dde.png)

**Comment by lexxakw** [comment]
> I have a question, have you edited this node type `Basic Quizlet Extended`? You should not edit this note type because the addon uses it. I would recommend you remove this note type and try to import one more time (the addon will re-create it). I've tried to import your deck and it works in both cases. p.s. make a backup of your anki before doing any changes :)
> 
> ![image](https://user-images.githubusercontent.com/19693768/216121141-c143ef6f-784d-4df0-9a20-a41859508dde.png)

I hadn't edited it, at least not to my knowledge (I'm not very experienced with the Anki program). I tried doing what you suggested and it fixed the issue! :)

**Comment by sviatoslav-lebediev** [comment]
Cool, happy it helped you :)
