### ISSUE TITLE
Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by williams314** [sviatoslav-lebediev/anki-quizlet-importer-extended#53]
**Describe the bug**
I keep getting this error message anytime I want to import a quizlet

**Quizlet deck URL**
https://quizlet.com/_cqmmfi?x=1jqt&i=1ji5u
https://quizlet.com/_cqv9pi?x=1jqt&i=1ji5u

**Additional context**
{"statusCode":500,"code":"ERR_NON_2XX_3XX_RESPONSE","error":"Internal Server Error","message":"Response code 403 (Forbidden)"}

**Comment by sviatoslav-lebediev** [comment]
Hi, as I wrote here https://ankiweb.net/shared/info/1362209126

```
The addon works with the "long" link format. If you have a link like this https://quizlet.com/_ma00ww, please open it in a browser and take the final link. Correct link will be like this https://quizlet.com/942000056/list-17-flash-cards/
```
