### ISSUE TITLE
 403 (Forbidden)"} I can't import quizlet decks after downloading add-on

### ISSUE THREAD

**Issue by takpamgbo14** [sviatoslav-lebediev/anki-quizlet-importer-extended#54]
I can't import any quizlet decks. I copy and pasted the add-on from ankiweb and still nothing.
I have tried with and without a US VPN.
Mac 13.2 (22D49)

https://quizlet.com/770269525/flash-cards/
**Additional context**
Error from the addon window
{"statusCode":500,"code":"ERR_NON_2XX_3XX_RESPONSE","error":"Internal Server Error","message":"Response code 403 (Forbidden)"}

**Comment by sviatoslav-lebediev** [comment]
it looks like this set is protected

```
Set Protected
Sorry, only the creator of this study set can access it.
```
is this set yours?

**Comment by takpamgbo14** [comment]
yes. I can unlock it and try again

**Comment by sviatoslav-lebediev** [comment]
ok, let me know if it helps.
