### ISSUE TITLE
cannot import quizlet

### ISSUE THREAD

**Issue by githubadventures** [sviatoslav-lebediev/anki-quizlet-importer-extended#55]
Error from the addon shows:
{"statusCode":500,"code":"ERR_NON_2XX_3XX_RESPONSE","error":"Internal Server Error","message":"Response code 403 (Forbidden)"}

quizlet link: https://quizlet.com/580287018/dirty-usmle-biochem-flash-cards/

Anki version is 2.1.54. I am in the US so didn't use a VPN

Thanks!

**Comment by sviatoslav-lebediev** [comment]
Hi, thx for letting me know. let's discuss it here https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/50
