### ISSUE TITLE
Image importing does not work with this quizlet

### ISSUE THREAD

**Issue by MaryClareGitHub** [sviatoslav-lebediev/anki-quizlet-importer-extended#56]
Image importing does not work with this Quizlet https://quizlet.com/363366586/chapter-1-diagram-2-of-6-openstax-anatomy-physiology-diagram/ any guidance on how to make images work would be appreciated I am using a mac :)

**Comment by sviatoslav-lebediev** [comment]
good question, let me take a look

**Comment by sviatoslav-lebediev** [comment]
I've released a new version, the addon will import images but not `shapes`. I guess it's possible to add support for `shapes` but it will definitely take time. I'm not sure that I have time now to add that feature.
Try to update the addon and re-import the deck. Let me know if something doesn't work.
