### ISSUE TITLE
Import from Quizlet No Longer Works

### ISSUE THREAD

**Issue by Cathnode** [sviatoslav-lebediev/anki-quizlet-importer-extended#57]
**Describe the bug**
When trying to import from Quizlet, an error message stating "Oops, that's not a Quizlet URL" pops up, although the link used is definitely one from Quizlet. Tried a previously working link as a test (with the import being successful previously), but it still failed this time.

**Quizlet deck URL**
https://quizlet.com/767478727/japanese-nouns-14-flash-cards/

**Additional context**
Image attached:
![image](https://user-images.githubusercontent.com/126412124/221426281-88747a0a-9c13-42de-9d98-b5bebe1aaa53.png)

**Comment by sviatoslav-lebediev** [comment]
Hi, correct me if I'm wrong but it looks like the old addon. My addon is here https://ankiweb.net/shared/info/1362209126
p.s. on the screenshot you mixed fields, you need to put a URL to the `Quizlet URL` field.

**Comment by Cathnode** [comment]
Aha that's embarrassing, swear I gotta stop working so late at night. 😅 Thanks for the pointer! No issue here

**Comment by sviatoslav-lebediev** [comment]
no problem :)
