### ISSUE TITLE
'NoneType' object has no attribute 'group' still poping up

### ISSUE THREAD

**Issue by Piotreusz** [sviatoslav-lebediev/anki-quizlet-importer-extended#58]
**Describe the bug**
I have a quizlet link that i want to study, but unfortunately the quizlet doesn't belong to me. For example this quizlet link "https://quizlet.com/128059152/import-to-anki-flash-cards/" works perfectly fine. If its about cookie and qlts settings, please i would very appreciate if someone would send a photo of how to do it. The link "that doesn't work" is set to pubic, because i can see the content while i am not logged into my quizlet account

**Quizlet deck URL**
The link that doesn't work:
https://quizlet.com/pl/779142163/mission-chapter-1-unit-34-flash-cards/?funnelUUID=72e009a0-5d3b-4dea-ae57-f09f6b9f8aa5
Alternative
https://quizlet.com/pl/779142163/mission-chapter-1-unit-34-flash-cards/

The link i tried  that works: https://quizlet.com/128059152/import-to-anki-flash-cards/

**Additional context**
Error from the addon window
'NoneType' object has no attribute 'group'
-----------------
<!DOCTYPE html><html lang="en-us"><head><meta charSet="utf-8"/><link href="/_next/static/media/q-twilight.e27821d9.png" rel="shortcut icon"/><link as="fetch" crossorigin="anonymous" href="/_next/static/media/icons.4abffb6c.svg" rel="preload"/><script>(function() {
    var ajax = new XMLHttpRequest();
    ajax.open('GET', "/_next/static/media/icons.4abffb6c.svg");
    ajax.send();

...

**Comment by sviatoslav-lebediev** [comment]
Hi, thank you for letting me know, I will take a look

**Comment by sviatoslav-lebediev** [comment]
I've recently added a proxy service, could you please try to import this `https://quizlet.com/pl/779142163/mission-chapter-1-unit-34-flash-cards/` one again? Let me know if it works if not I will try to find why
