### ISSUE TITLE
Reversing and writing issue

### ISSUE THREAD

**Issue by donger884** [sviatoslav-lebediev/anki-quizlet-importer-extended#59]
Hello, I used your add-on to import my quizlet sets, but I have no clue how to set them up for writing in the answer or even reversing the cards properly.

All my Quizlet sets are set up like Front - Arabic, Back - English. 
I figured out that I can flip them through Browse -> Cards... and then selecting "flip" at the bottom, but then it changes that for ALL imported decks and not just the deck I want flipped. How do I this only for specific decks?

And I know how to create cards to write in the answer, but I dont know how to convert the imported decks, while also retaining the audio.

**Comment by sviatoslav-lebediev** [comment]
Hi, as for me you need to read how anki `Note Types` work. This addon creates a "system" note type - "Basic Quizlet Extended". **You should not change this type.** You need to create a separate note type or clone "Basic Quizlet Extended". After that - just change your imported items note type. When you create a new note type it will have cards. You will be able to create a card that supports typing. For example this is a card template example
```
<span class="deck_name">{{Deck}}</span>
<br />
<br />

{{Front}}
<br/>
<br/>
{{type:Back}}
```
![image](https://user-images.githubusercontent.com/19693768/223499760-a2d42e32-07c2-4515-a5e1-a83d5a1e9e59.png)


More info https://docs.ankiweb.net/getting-started.html#note-types

**Comment by sviatoslav-lebediev** [comment]
https://www.youtube.com/watch?v=5tYObQ3ocrw
