### ISSUE TITLE
error when importing from Quizlet

### ISSUE THREAD

**Issue by elodiesparrow1** [sviatoslav-lebediev/anki-quizlet-importer-extended#60]
i try to import quizlet sets to anki and it just comes up with :

'NoneType' object has no attribute 'group'
-----------------
<!DOCTYPE html>

[**Quizlet deck URL**](https://quizlet.com/_9yofw6?x=1jqt&i=3qhs17)

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Hi, this addon doesn't support "short" links, could you please try to open that link and use the final link ?
Final link will be `https://quizlet.com/gb/602442870/hsk-5-flash-cards/?x=1jqt`

**Comment by sviatoslav-lebediev** [comment]
I've tried to import your quizlet set and looks like everything works correctly
Here is a final file https://www.filemail.com/d/dkcllezgrzitvdk
