### ISSUE TITLE
bug can not improt from quizlet

### ISSUE THREAD

**Issue by niiteLite** [sviatoslav-lebediev/anki-quizlet-importer-extended#61]
**Describe the bug**
nonetype object has no attribute group copied directly from url 

**Quizlet deck URL**
https://quizlet.com/619028862/leccion-6-portales-flash-cards/
**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
I've tried to import this deck and it looks like everything is ok. Usually, it means that something is wrong with a network and quizlet returns an incorrect response. I would try to use some VPN.

I've created a apkg file that you can try to add to your anki

[Leccion 6 Portales.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11032489/Leccion.6.Portales.apkg.zip)

**Comment by niiteLite** [comment]
yes i see now! just realized i've been using an outdated version for several months, reinstalled works perfectly. has saved me countless hours over the last few months. thank you

**Comment by sviatoslav-lebediev** [comment]
Oh, nice. Happy to hear that :) I'm going to close this ticket, if you have any questions/propositions don't hesitate to create a new ticket.
