### ISSUE TITLE
Cant upload deck even though it is not private 

### ISSUE THREAD

**Issue by sorchace** [sviatoslav-lebediev/anki-quizlet-importer-extended#63]
I cannot upload my decks from quizlet to anki even though they are no longer private 

https://quizlet.com/728135160/flashcards

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Could you please try this url https://quizlet.com/ch/728135160/skeletal-spinal-anatomy-flash-cards/ ?
