### ISSUE TITLE
Unable to upload flashcards despitee them being public

### ISSUE THREAD

**Issue by blancqueen** [sviatoslav-lebediev/anki-quizlet-importer-extended#64]
Keep getting the error "Sorry, this deck is private" when trying to upload flashcards despite the deck being public

https://quizlet.com/gb/787847858/biology-topic-1-flash-cards/

"Sorry, this deck is private" is the message I get

**Comment by sviatoslav-lebediev** [comment]
Hm, I've tried to import this URL, and looks like everything works correctly
Could you please provide a screenshot?
p.s. almost 99% of all problems with this addon are related to network issues. Could you try to use a VPN?

here is your deck
[Biology Topic 1.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11102840/Biology.Topic.1.apkg.zip)

**Comment by blancqueen** [comment]
Tried with a VPN, now get unknown error
<img width="478" alt="Screenshot 2023-03-30 at 10 51 59" src="https://user-images.githubusercontent.com/76822084/228799012-ef3cab4e-c1f8-44e9-961f-ac3cef8fe4c6.png">

**Comment by sviatoslav-lebediev** [comment]
ok, this one means that quizlet for some reason returns an incorrect response. I will take a look on the weekend.

**Comment by sviatoslav-lebediev** [comment]
could you try to install this version ? https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/releases/tag/v2023.04.03-1

**Comment by sviatoslav-lebediev** [comment]
I've updated the version, could you please try to update the add-on ?
