### ISSUE TITLE
Card stop importing 2nd April update

### ISSUE THREAD

**Issue by TroubledAnkiUser** [sviatoslav-lebediev/anki-quizlet-importer-extended#65]
Hi

The addon has stopped imporitng cards and returning a "deck is private" error. \i tried again with a URL that worked just yesterday before the update, and the same issue

New URL tried:

https://quizlet.com/gb/276563564/stimmt-1-kapitel-5-snacks-und-getranke-kaufen-flash-cards/?funnelUUID=e33c08b4-b2f6-4db5-be3c-87b71c94e9ee

Previously working now with error:

https://quizlet.com/213462148/stimmt-1-kapitel-4-oft-benutzte-worter-flash-cards/?funnelUUID=18b42cd4-1a95-46c9-91a7-37f999102f56

Thanks

**Comment by sviatoslav-lebediev** [comment]
Hi, thx for letting me know, I will take a look

**Comment by sviatoslav-lebediev** [comment]
it looks like for some reason anki returns the old version of the add-on. could you please share your add-on files ?
I want to double-check that you have the latest version
![image](https://user-images.githubusercontent.com/19693768/229482456-00c59db4-382f-4c6d-a489-65682ee8f42c.png)
![image](https://user-images.githubusercontent.com/19693768/229482561-1853d60b-dc0d-4025-afa2-1eb250c922bd.png)

**Comment by TroubledAnkiUser** [comment]
Thank you. PLease find attached the files.
[New folder.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11141453/New.folder.zip)

**Comment by sviatoslav-lebediev** [comment]
yes, this version is old, I don't understand why anki server returns this version :(
could you try to take this file https://raw.githubusercontent.com/sviatoslav-lebediev/anki-quizlet-importer-extended/master/__init__.py and update your __init__.py file ?

**Comment by sviatoslav-lebediev** [comment]
or try to install this add-on from the https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/releases

**Comment by TroubledAnkiUser** [comment]
Thank you - reinstalling from your link worked.

**Comment by sviatoslav-lebediev** [comment]
oh, cool, thx for letting me know. I've asked anki developers why I can't update the add-on version, I hope they will help to fix this issue.
