### ISSUE TITLE
Quizlet set empty once imported

### ISSUE THREAD

**Issue by JoshJee00** [sviatoslav-lebediev/anki-quizlet-importer-extended#66]
Set seems to import fine, but then returning into 'Decks' or 'Browse' in Anki, there are no cards present.

Happening repeatedly but e.g, for: https://quizlet.com/779544271/arabic-vocab-hilary-2023-set-1-flash-cards/?funnelUUID=9eae7cbb-1d2f-4d66-9d96-2ff71e9ea4b4

**Comment by sviatoslav-lebediev** [comment]
Hi, for some reason I can't reproduce. Here is what I see
![image](https://user-images.githubusercontent.com/19693768/232109468-451b822d-dd4a-4699-a249-e570b03b0728.png)

**Comment by JoshJee00** [comment]
Interesting. I'll try reverting to the older version of Intel Anki for Mac and see if that changes things.

**Comment by sviatoslav-lebediev** [comment]
my versions
Version ⁨2.1.61 (0c1eaf4c)⁩
Python 3.9.15 Qt 6.3.2 PyQt 6.3.1

**Comment by JoshJee00** [comment]
Same version, and on intel Qt. Have tried reverting and updating. No luck yet. Will continue to play around.

**Comment by sviatoslav-lebediev** [comment]
hm, interesting. And it doesn't throw any errors, right? And you see the progress 1/88?
You can try to remove the add-on and install it from here https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/releases/tag/v2023.04.03-1 manually

**Comment by JoshJee00** [comment]
issue remains.

**Comment by JoshJee00** [comment]
Have found a strange fix, when I download, having chosen to create reverse cards, the set imports properly... very strange but now working. Thanks, will get you a coffee..!

**Comment by sviatoslav-lebediev** [comment]
:) no problem, happy to help. One thing that sometimes happens is that users edit this note like ``Basic Quizlet Extended'', I don't know, maybe you edited it too. This app uses this type of note, so it's best to leave it as is.
