### ISSUE TITLE
What format should my set cookies be in for a private deck?

### ISSUE THREAD

**Issue by rjimenez156** [sviatoslav-lebediev/anki-quizlet-importer-extended#67]
Here is what I have tried in the {
    "cookies": "",
    "qlts": ""
}
while True:
            try:
                r = None
                config = mw.addonManager.getConfig(__name__)
                cookies = {}
                if config["qlts"]:
                    cookies = {"qlts": config["qlts"]}
                elif config["cookies"]:
                    from http.cookies import SimpleCookie
                    C = SimpleCookie()
                    C.load(config["cookies"])
                    cookies = {key: morsel.value for key, morsel in C.items()}

https://quizlet.com/793053424/flash-cards/

set-cookie: qlts=1_QHKIbsBpYgmlHw3KPL2cWIJqLBoGKmZPdHyon-LHhTJ2Cics2lpaihol-UJIUy43Dmo1WW6hKcdE; expires=Sun, 19-May-2024 05:40:42 GMT; Max-Age=34560000; path=/; secure; httponly
1_QHKIbsBpYgmlHw3KPL2cWIJqLBoGKmZPdHyon

**I am probably just in the wrong format, I appreciate the help!**

Unkown Error from the addon window:

'cardSides'
-----------------
{"responses":[{"models":{"studiableItem":[{"id":1763210211389442,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535980},{"id":1763210320441345,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535980},{"id":1763210334093312,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535980},{"id":1763210350882816,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535980},{"id":1763214663626754,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214679347203,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214708752384,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214721335296,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214736035840,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214756958208,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214770610178,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214770610179,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214786363396,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214828244993,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214846087168,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214862868480,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214877569024,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214890147841,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214927908866,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214944653312,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763214955122688,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763215049539585,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763215109304321,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763215122931712,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763216782843904,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763216827891713,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763216871976960,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763216885616640,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763216901283840,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217026080769,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217054437377,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217071157248,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217117298688,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217138290689,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217211658240,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217224241153,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217239994369,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217263075329,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217276727298,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217288253442,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217314484225,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217330143232,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217341681664,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217367941120,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217380503552,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217394155520,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217405702144,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217433960448,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217445498881,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217468616704,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217480110082,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217490608128,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217580752897,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217595482112,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217611202560,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501},{"id":1763217631088640,"studiableContainerType":1,"studiableContainerId":793053424,"isDeleted":true,"lastModified":1681535501}]},"paging":{"total":56,"page":1,"perPage":1000,"token":"cvCu3sJshv.8gRaZp87gEXfm8e3E"}}]}

**Comment by sviatoslav-lebediev** [comment]
Hi, I guess you need to copy just a value
![image](https://user-images.githubusercontent.com/19693768/232441672-254e5b78-1203-4900-b2f0-4ddf224e55e8.png)

**Comment by sviatoslav-lebediev** [comment]
second option - make it public, import, make it private

**Comment by sviatoslav-lebediev** [comment]
happy to help, thanks for the coffee
