### ISSUE TITLE
Audio download problem

### ISSUE THREAD

**Issue by kazemihabib** [sviatoslav-lebediev/anki-quizlet-importer-extended#68]
**Describe the bug**
I realized that the addon does not download the Audio, I investigated the code and realized that 
https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/blob/master/__init__.py#L389
```
r = requests.get(url, stream=True, verify=False, headers=headers)
        if r.status_code == 200:

```
r.status_code returns 403

The weird thing is that when I tried running the `fileDownlaoder` function myself, it return 200 but in Anki it doesn't work. 
I also tried to download it with `urllib` instead of `requests` in the addon and it returned 200 and the problem was solved.

**Quizlet deck URL**
https://quizlet.com/52722720/11-ciak-saluti-e-presentazioni-vocaboli-flash-cards/

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Hi, could you please provide that code with `urllib`? Previously I haven't seen any issues related to the audio downloading.

**Comment by sviatoslav-lebediev** [comment]
Hm, I've tried to import ^ deck and it looks like everything is on, I see audio for all cards.

**Comment by Mdt78** [comment]
I have the same problem, like the audio icon is there but when I press on it I can hear nothing.
This happened after the last update. It was just fine before that.

**Comment by kazemihabib** [comment]
@sviatoslav-lebediev  sorry for my slow response, here is the urllib code:

https://github.com/kazemihabib/anki-quizlet-importer-extended/commit/b380671d1c8622fe70ecc9c21b3ae58f79aed107

**Comment by sviatoslav-lebediev** [comment]
> I have the same problem, like the audio icon is there but when I press on it I can hear nothing.
> This happened after the last update. It was just fine before that.
Could you please provide the deck URL ? The last update added just 1 thing - if we can't download data in the common way we are trying to fetch using "internal" API.

**Comment by sviatoslav-lebediev** [comment]
> @sviatoslav-lebediev sorry for my slow response, here is the urllib code:
> 
> [kazemihabib@b380671](https://github.com/kazemihabib/anki-quizlet-importer-extended/commit/b380671d1c8622fe70ecc9c21b3ae58f79aed107)

Thx, if I receive more complaints about this issue I will try to use your changes.
p.s  @kazemihabib are these urllib and urllib2 internal libs? Users will not need to install them, right? I'm not a Python dev :)

**Comment by kazemihabib** [comment]
Yes, they are internal libs.

**Comment by sviatoslav-lebediev** [comment]
got it, thank you

**Comment by sviatoslav-lebediev** [comment]
going to close this issue, I've updated the add-on, now it uses the @kazemihabib approach.
