### ISSUE TITLE
Quizlet to anki mac

### ISSUE THREAD

**Issue by Jackiee2020** [sviatoslav-lebediev/anki-quizlet-importer-extended#7]
https://quizlet.com/522306141/superficial-and-deep-back-mm-flash-cards/

I continue to get the error after downloading the quizlet to Anki 
please help

**Comment by Jackiee2020** [comment]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-05 13:52:02
Add-ons possibly involved: ⁨Improved Quizlet to Anki 21 Importer⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/jacquelinejean-gilles/Library/Application Support/Anki2/addons21/538351043/__init__.py", line 291, in onCode
    self.createDeck(deck)
  File "/Users/jacquelinejean-gilles/Library/Application Support/Anki2/addons21/538351043/__init__.py", line 320, in createDeck
    terms = result['terms']
KeyError: 'terms'

**Comment by sviatoslav-lebediev** [comment]
Have you updated a version of the addon?  Here is a screenshot of the new version
Do you have a `Download audio` checkbox? If not try to remove and install the addon again.
![image](https://user-images.githubusercontent.com/19693768/92311335-d683ad80-efbe-11ea-8262-4ac8a16a1da0.png)

**Comment by sviatoslav-lebediev** [comment]
Oh, I know why you have this problem :) You are using a different addon. You need to install this one https://ankiweb.net/shared/info/1362209126

**Comment by Jackiee2020** [comment]
Thank you so much

**Comment by sviatoslav-lebediev** [comment]
sure, np
