### ISSUE TITLE
"KeyError: 'BackText'" with this importer.

### ISSUE THREAD

**Issue by Alapalathus** [sviatoslav-lebediev/anki-quizlet-importer-extended#71]
Hello,

I've been using your importer for a while, but it's suddenly stopped working (error message from anki below)? It seems to create the deck in anki but doesn't manage to import any cards (the deck itself is completely empty).

https://quizlet.com/gb/797698454/81-vivre-ensemble-82-les-defis-et-les-bienfaits-de-limmigration-et-du-multiculturalisme-83-les-enjeux-du-multiculturalisme-en-france-flash-cards/

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-04-28 16:13:41

Caught exception:
Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'BackText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PETER PARKER\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 294, in onCode
    self.createDeck(deck)
  File "C:\Users\PETER PARKER\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 342, in createDeck
    note["BackText"] = item["definition"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'BackText'

Any advice would be very greatly appreciated!

**Comment by sviatoslav-lebediev** [comment]
Maybe I'm wrong but I think you have changed the `Basic Quizlet Extended` note type. It's a "system" note type and I would not recommend editing it. Try to remove it `Tools/Manage Note Types`, the add-on will re-create it.

**Comment by Alapalathus** [comment]
Thank you! I think its working now.

**Comment by sviatoslav-lebediev** [comment]
Cool, happy to help :)
