### ISSUE TITLE
Can't select neither add audio or add reverse

### ISSUE THREAD

**Issue by giulia1235** [sviatoslav-lebediev/anki-quizlet-importer-extended#72]
When importing a set from quizlet, I can't select any option (add reverse or audio). I want to add reverse for every quizlet set I want to import. Here is just an example of my set that doesn't work. I also tried different set from other users but the problem remains. 

https://quizlet.com/it/791068443/j403-u1-%E8%AA%9E%E5%BD%99-flash-cards/?funnelUUID=2c4f626f-933f-4297-93c1-cb21844cdd64

![image](https://user-images.githubusercontent.com/132179692/235332765-3d51d010-55b8-42ca-8776-b1ce4fc3d109.png)

**Comment by giulia1235** [comment]
the squares of the options remain blank even if you click it

**Comment by sviatoslav-lebediev** [comment]
Hi, it's interesting, I haven't seen this error before. Could you take a look at what Anki version you have?
