### ISSUE TITLE
Images not showing up

### ISSUE THREAD

**Issue by rashaddddd** [sviatoslav-lebediev/anki-quizlet-importer-extended#76]
**Describe the bug**
The images do not show up when I import the deck. 

**Quizlet deck URL**
https://quizlet.com/803385892/photosynthesis-a-diagram/?funnelUUID=d3ceef5a-863a-4f64-b7a0-3ab592a861c5

**Additional context**
There is an image icon, but I cannot see the image itself

**Comment by nazismail** [comment]
hi, same thing happeneidng with me, it shows an image icon but wont let me see the image.
<img width="1246" alt="Screenshot 2023-05-17 at 18 18 42" src="https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/133904136/b24e638d-343f-4b41-8898-9802b8a87420">

**Comment by nazismail** [comment]
would it be possible to fix this please?

**Comment by sviatoslav-lebediev** [comment]
I'm working on it

**Comment by sviatoslav-lebediev** [comment]
could you try to update the add-on and re-import ?

**Comment by sviatoslav-lebediev** [comment]
I will close this ticket, re-open it, or create a new one if you still can't import decks.
