### ISSUE TITLE
Can't download audio

### ISSUE THREAD

**Issue by rossc123** [sviatoslav-lebediev/anki-quizlet-importer-extended#77]
**Describe the bug**
Whenever I try tick the "downlaod audio" checkbox I receive  an error. However, importing a deck without audio works fine.
I am using Anki Version 2.1.63

**Quizlet deck URL**
https://quizlet.com/kr/764520676/new-kiip-level-4-vocab-grammar-unit-1-%ED%95%9C%EA%B5%AD-%EC%83%9D%ED%99%9C-%EC%A0%81%EC%9D%91-adaptation-to-life-in-korea-flash-cards/ 

**Additional context**
Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Captcha Challenge…</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAlNJREFUOE9VUz1IVWEYfp7vemkwMVpqlIKGiExFAxvUc0loCSqPNwJBshwatKUpGoL2rKbkolKTd3DISaGrEA32YxnZ1O/WJIYU5vV&#43;T3w/52JnuOfynvd9/t7vI/Y8BNA3qHYIowASQS0AQeg7gSUZPq7McrU&#43;QvfNTQno71fjbrMeSRx2dQpuFpJAuibACgIxtX9bY/PzuT&#43;u5j/1D9nG6jYXAXR7vDhcZ1JodOXwgxf5LZxbWDC/PXQyYKdBDodJD7sGYcLksGKtnKAuAGMS2rxi36PpSjl3lYWi7YTliuAbHcHMr68YXX1rqk5xJrO93eabj3AS0HDIBUJNp9mX2hKBkdDLtc2D6Hw3yapiNpHO59Fx3eabN/AGxElHJaLEJNVnAEedfBmOLJU55aG8GpdZ0BzUEL2pHTFAKRr5wmRAVRINrkGGp5ZmuZaR198xQLeZnqJajcX7AKCqA9gGtM9rNOiolN2e4&#43;h/NkK1J7UdRnQ2nKwdZ2EdwHG/Z2p8uWwe&#43;lZH54LwDuJ2RBRSOy5gwhsUPzEZtPch3oxt33b&#43;qvXlM7NVJ9/j48x527Qvjw&#43;gWuLGHrBQ1DFZfASQD&#43;vFYq0JxeUZbjriLMzeC/aAaWAZ0Flfk3YFnvAhJ5d0D8TtGLdD&#43;UmxJINXQYC6IF4DdDgDBPja1nDRO0xT5TaAJxKuePvZ4uQuRcw7rtQd1uyiSJrLDiZw15pknbdgcQdEYzaWwfljTlYZrcbrMucJwiEM/wqXdQg1DElKILa4cg34AaBC6CnFNgA3SHVLfP4PI2gOacTNpN0AAAAASUVORK5CYII="/>
    <link rel="icon" type="image/png" sizes="32x32" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAABZFJREFUWEell3uIFXUUxz9n7truapnZoqKUiQgZZhJGbabcvTdNQ8PHnZu2JRo9SCL8J4mMMAqlEMFAAyF7&#43;ryrmBWKePcuWEaGZEJrf2SlmcS6JRbrru7dOTHPOzN3dveP5o/duTPn8T3nfM85vxHsS0DUucP5J&#43;69&#43;8O9sgv1VmqYawlNAtOAO4BbHBnhMug5UTmFQclKcbi0Szor2rbBkDHHgTp/JfwqKub&#43;ypp6l6WsMYScwrCK0bh534GDvkuUFoR3igVpj0tW3NsgbAgaRueKz2vW4dev8ZYKzwM3&#43;OCc/27UlSx5966MVtIoXBdha8&#43;NvP71dvm3P/B&#43;FVDPS3qRTjFSWkDkziSl4FkYSJWg&#43;9Iz2S5gFluk3cYnIm5B1C2DWwgvC7PzOqNPOQg6shJm/9UcEKDPI9fLJYH5xYKcCOuIjdFJGzDL1LuHQJvCSI9csTx76XWYU12CQcFAp1qkS/vkx1BJ3duHTb3Zgu9AJ0Uir07zeeBL4ITAH14Wx6HcpwbzBW6rBhIyovzUVav3f7vD&#43;McvkSOfMXUr8EIkMqc8nrJyQWFtXRd7Dh0yrrlMC/MZ5s3T2u7h5AxL14PcHmFpCIMoW1pb5MWAJdnFOlWFk4jWuCWpuo5Y3TS3fRHu7f4Tnl5gNRi1sgNhTrSUgU6vWExv3SennWJm8roTZVlSYQWOXIWF3xSk26d0EiXjo6Yxp/X1wgFgThyqLWvBzlJBmiW7TEdrmd8E6twetsdikLzftYZ723ZJZ&#43;Ag5CnuNOJIIL1UG1JlTgHjXKKHyAvdUsMEyeR0JcJ2Xzk6GXVlsWB8&#43;D&#43;a0ObWCuCDxLZRnpamvPWRqCx3J5wzJVxZ4aLVwcS2NulJGtHxaJOIY8uk01pnjOIsytgKcQPtTyRjqp2ie&#43;J1Uni/VJBnfKZH31cnf6ByZPK6HWVlFW2V0zaAy8AId0RGdtaq1oK8N/hwGZAJjnpTTlcJbAlaulLvyzaAPsCIp0eVJaUW2T8ggJjvRCgCTaYuEdUWn4T2aHH2DmrZJOxFqElwlG8tSCF4XmV98Mh93aa85kXZEyGiu/nKkjGtP0FGB43nt4rwcute2VgFLBGIE02/ycrmdI0KbzsClQFql7zDLsFxoDGi7QodKBVkUdRsQtSR80RyVjKmfgY8lkDC45LN6WYVXkpoka5emHCsIJeSQgtv0aQZ4j&#43;b85SOKnfzK6JD4&#43;tdlHdtDswHPo8OKa8gyvq2FlnrZiEpusF5kDV1g6KvJB2hRFkgjabW18MvwJgISezTjNJtCTNLBTmZHGV4G3on21CNZy/R6X0Gx4C6aBYdoY4rPUxwmiGd1zcN5bVEFinnSJFt3SNnE4dREi3s3n9cJ2JRBMYnOLcJuKG4V151ASzVBsPiDEpDNQgH7QURlhf3Sqm6GtUI0qamDfgUdFx4s4XK/HdNmclHDkiHu/pE7aXxLMo2h4zORoxvLy0jstvoY9PRffwAYrlgvd2xzjIyZ5iGxWqUJxBSSZHbzyxY3dYimwNtJ4Z1amTb2a2K2U8W/FFhH2V/RjipykXHiDBWlemiTPQOwr6sh885/4cnRVGVj7XMwcqCFpixQG&#43;qreUw8GB4aAzI9fBRKz6OvHf96WsfzZETgsOHFdYIo0vswTErkZQJ0yTa3wN&#43;LASZcbZ&#43;mSerANgSD5haP1TZhPCcu6gS&#43;e8d6BNNBAqR6GPYpNcH4NsIf94pNOX1EUPZiDLF217xWg5IF5S/EEYGTI2Vq98MBENHYHJObxgFiwycb8QZ9ndisleP00qvir1fZJsOY3/qKnPV4g2EqYFd7/QlfbESROa7n7tgwAmPmn1jelRmquF8no83VEfYLaDKFeC8WnyfGsJXR3eL0x3&#43;ZZqa6kQfEpGFWDQKTHI&#43;7Q0W/wfl0z3FmuKBUQAAAABJRU5ErkJggg=="/>

**Comment by sviatoslav-lebediev** [comment]
Hi, i will take a look.

**Comment by sviatoslav-lebediev** [comment]
quizlet has changed something , I need time to fix this

**Comment by sviatoslav-lebediev** [comment]
@rossc123 try to update the add-on. I hope it will help you with audio
p.s. please let me know if it helps

**Comment by sviatoslav-lebediev** [comment]
sure, np, thank you for letting me know :) from time to time quizlet adds some protection and i need to fix import again
