### ISSUE TITLE
i can't import any decks at all

### ISSUE THREAD

**Issue by practicalchemi** [sviatoslav-lebediev/anki-quizlet-importer-extended#78]
this space doesn't have enough characters to fit the entire message but it starts off like this: 

Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Captcha Challenge…</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAlNJREFUOE9VUz1IVWEYfp7vemkwMVpqlIKGiExFAxvUc0loCSqPNwJBshwatKUpGoL2rKbkolKTd3DISaGrEA32YxnZ1O/WJIYU5vV&#43;T3w/52JnuOfynvd9/t7vI

**Comment by sviatoslav-lebediev** [comment]
could you provide some links that you were trying to import ?

**Comment by practicalchemi** [comment]
https://quizlet.com/gb/783152174/ownership-and-control-traditional-marxism-flash-cards/?funnelUUID=e498fc90-cdc5-4bf0-9b6e-1ccc05727814

https://quizlet.com/gb/783524859/ownership-and-control-neo-marxism-flash-cards/?funnelUUID=0692caa1-2bf7-4be2-a7db-b2fde7f644aa

https://quizlet.com/gb/783802937/ownership-and-control-postmodernism-flash-cards/?funnelUUID=017ddc20-9b18-48ed-b3a7-48f3271bf280

https://quizlet.com/gb/783537270/ownership-and-control-pluralism-flash-cards/?funnelUUID=e6ffea35-5c2e-4813-837d-100ed00f6c83

https://quizlet.com/gb/775178890/preparation-of-aspirin-flash-cards/?funnelUUID=80b9f2b2-228c-4810-9a15-77459040dd6e

https://quizlet.com/gb/788357676/amines-flash-cards/?funnelUUID=2a7622e8-cfd7-47bc-beb7-76b7ad90c775

https://quizlet.com/gb/788369781/polymers-flash-cards/?funnelUUID=0dab4ae7-7e77-4b71-b965-1ea645cbd8a6

**Comment by sviatoslav-lebediev** [comment]
quizlet has changed something , I need time to fix this

**Comment by sviatoslav-lebediev** [comment]
@practicalchemi try to import a few times or try to use some VPN. It looks like from time to time quizlet protects their pages, that's why the add-on can't fetch data. I will try to fix this but it will take time

**Comment by sviatoslav-lebediev** [comment]
I've added an ability to set quizlet HTML manually. Try this approach and let me know if it works for your case. I will close this ticket, re-open it, or create a new one if you still can't import decks.
