### ISSUE TITLE
Error when trying to import public deck - HELP!

### ISSUE THREAD

**Issue by Alex-Epstein** [sviatoslav-lebediev/anki-quizlet-importer-extended#79]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.63 (f356f177) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-12.6-arm64-arm-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-05-17 09:35:42
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "urllib3.connectionpool", line 703, in urlopen
  File "urllib3.connectionpool", line 386, in _make_request
  File "urllib3.connectionpool", line 1042, in _validate_conn
  File "urllib3.connection", line 419, in connect
  File "urllib3.util.ssl_", line 449, in ssl_wrap_socket
  File "urllib3.util.ssl_", line 493, in _ssl_wrap_socket_impl
  File "ssl", line 501, in wrap_socket
  File "ssl", line 1041, in _create
  File "ssl", line 1310, in do_handshake
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests.adapters", line 489, in send
  File "urllib3.connectionpool", line 787, in urlopen
  File "urllib3.util.retry", line 550, in increment
  File "urllib3.packages.six", line 769, in reraise
  File "urllib3.connectionpool", line 703, in urlopen
  File "urllib3.connectionpool", line 386, in _make_request
  File "urllib3.connectionpool", line 1042, in _validate_conn
  File "urllib3.connection", line 419, in connect
  File "urllib3.util.ssl_", line 449, in ssl_wrap_socket
  File "urllib3.util.ssl_", line 493, in _ssl_wrap_socket_impl
  File "ssl", line 501, in wrap_socket
  File "ssl", line 1041, in _create
  File "ssl", line 1310, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(9, 'Bad file descriptor'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1003354/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 521, in getDataFromPage
    r = requests.get(url, verify=False,
  File "requests.api", line 73, in get
  File "requests.api", line 59, in request
  File "requests.sessions", line 587, in request
  File "requests.sessions", line 701, in send
  File "requests.adapters", line 547, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(9, 'Bad file descriptor'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1003354/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 596, in run
    self.getDataFromPage()
  File "/Users/1003354/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 591, in getDataFromPage
    e, r.text)
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by sviatoslav-lebediev** [comment]
quizlet has changed something, I need time to fix this

**Comment by avaninosos** [comment]
Just adding an observation for this. There seems to be a race condition somewhere. If I keep retrying to import over and over, it eventually imports.

**Comment by sviatoslav-lebediev** [comment]
It looks like they have added an additional protection. If you open the required page in a browser they return a correct page, otherwise, they return a "captcha page". I will take a look how we can fix this

**Comment by sviatoslav-lebediev** [comment]
@avaninosos yes, if you try a few times it can help, but I don't think it's a race condition, it looks like a quizlet algorithm somehow decides when it should protect the page.

So guys try to import a few times or try to use a VPN. I will try to fix this but it will take time
If you have any suggestions - please let me know

**Comment by seedling3088** [comment]
I'm getting the same error message as well while importing. It always happens exactly at card 65. I wonder if it is just for certain decks because I imported another deck an hour ago without a problem

**Comment by sviatoslav-lebediev** [comment]
@seedling3088 could you please provide a deck link ?

**Comment by seedling3088** [comment]
@sviatoslav-lebediev https://quizlet.com/271825534/cha-101l-quiz-6-flash-cards/?funnelUUID=ecb95d05-1dc2-406a-b114-559b98c06321

**Comment by sviatoslav-lebediev** [comment]
@seedling3088 I've added an option `Skip errors`. Could you try to update the add-on, select `Skip errors` and try to import again ? 
It will skip that "broken" image and import the rest of the cards.

**Comment by seedling3088** [comment]
> @seedling3088 I've added an option `Skip errors`. Could you try to update the add-on, select `Skip errors` and try to import again ? It will skip that "broken" image and import the rest of the cards.

I'll try that!

**Comment by seedling3088** [comment]
> @seedling3088 I've added an option `Skip errors`. Could you try to update the add-on, select `Skip errors` and try to import again ? It will skip that "broken" image and import the rest of the cards.

Thank you so much for the update! I was able to download the deck. When I look at the 65th card on quizlet it seems to be fine, how did you figure the image was "broken"? Thank you again so much! I was dreading copy pasting everything haha

**Comment by sviatoslav-lebediev** [comment]
@seedling3088  I've checked and as for me that image is ok, but for some reason, quizlet doesn't allow to fetch it. 
So this "skip errors" option is a quick fix, I will need to look at why the add-on can't download that image. But it's better to skip some images than fail the import.

**Comment by sviatoslav-lebediev** [comment]
I've added the ability to set Quizlet HTML manually. Try this approach and let me know if it works for your case. I will close this ticket, re-open it, or create a new one if you still can't import decks.

**Comment by Alex-Epstein** [comment]
@sviatoslav-lebediev I tried with the HTML and got an error. I'm on Version ⁨2.1.64 on windows. Here's the public deck I'm using: https://quizlet.com/802393436/vocab-words-flash-cards/

Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Captcha Challenge…</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8........... (keeps going for a long time)

**Comment by sviatoslav-lebediev** [comment]
@Alex-Epstein If you don't need audio try to uncheck `Download audio`, HTML without audio should work 100%.
I've tried to import your deck and it works

[Vocab words.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11593837/Vocab.words.apkg.zip)

**Comment by Alex-Epstein** [comment]
I just tried it again only using the URL and for some reason it worked. Lol. Thanks!

**Comment by Alex-Epstein** [comment]
One more question, does the Anki deck update when I change the quizlet deck?

**Comment by sviatoslav-lebediev** [comment]
@Alex-Epstein 
```
I just tried it again only using the URL and for some reason it worked. Lol. Thanks!
```
that's because Cloudflare somehow decides when it should protect the page. That's why I recommend to try a few times


```
One more question, does the Anki deck update when I change the quizlet deck?
```
could you elaborate please ? If you import a few different decks the add-on will create several decks. If you import the same deck 2 times you will have duplicates

**Comment by Alex-Epstein** [comment]
Sorry, I mean when I add/remove a card from the Quizlet deck, does it
update the deck in Anki? I'm guessing no.
