### ISSUE TITLE
Decks won't fully download

### ISSUE THREAD

**Issue by randomgithublad** [sviatoslav-lebediev/anki-quizlet-importer-extended#8]
https://quizlet.com/gb/513846792/coition-flash-cards/
https://quizlet.com/gb/505488178/hormone-regulation-and-gonadal-function-flash-cards/

both these decks aren't downloading all the cards, it did download all cards for two other decks I tried though

I don't want the audio feature, but it didn't work w or w/o audio enabled.

Thank you for fixing it so quickly, I have exams in a few days and the remainder of my decks are on quizlet and need importing to anki so I was very stressed until you updated.

Bet wishes

**Comment by sviatoslav-lebediev** [comment]
https://quizlet.com/314331873/p45-b2-antimicrobials-inhibitors-of-protein-synthesis-aminoglycosides-tetracyclines-macrolides-j-lockman-flash-cards/
This deck can't be fully imported as well
I will try to fix it

**Comment by sviatoslav-lebediev** [comment]
@randomgithublad fixed, try to update addon
