### ISSUE TITLE
Images not showing up

### ISSUE THREAD

**Issue by ajspecial** [sviatoslav-lebediev/anki-quizlet-importer-extended#80]
**Describe the bug**
for some reason images are not showing up .

**https://quizlet.com/gb/801766239/musculoskeletal-06-crystal-arthropathies-and-rheumatoid-arthritis-dr-jennifer-christie-flash-cards/?funnelUUID=1657af6a-808f-41d5-9f5b-4775a2a25c0e**

**Additional context**
 someone ha reported this please its exam season can you fix this

**Comment by sviatoslav-lebediev** [comment]
duplicate https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/76
