### ISSUE TITLE
Images not showing up once deck is imported

### ISSUE THREAD

**Issue by saravananep** [sviatoslav-lebediev/anki-quizlet-importer-extended#81]
**Describe the bug**
A description of what the bug is.
Getting an image icon for the pictures that were supposed to be downloaded from a public deck.

**Quizlet deck URL**
https://quizlet.com/798513708/lecture-33-36-odontogenic-cysts-non-odontogenic-cysts-flash-cards/

**Additional context**
Error from the addon window
Really appreciate this add -on tho! Exam coming up and this is a life saver!

**Comment by sviatoslav-lebediev** [comment]
duplicate https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/76
