### ISSUE TITLE
Private deck, but it is not.

### ISSUE THREAD

**Issue by nmeshkati** [sviatoslav-lebediev/anki-quizlet-importer-extended#83]
**Describe the bug**
I used the new add on and it keeps telling me that the deck I try to import is private, but it is not.

**Quizlet deck URL**
https://quizlet.com/_dat2ap?x=1jqt&i=mlhzc

**Additional context**
Error from the addon window

"Sorry this is a private deck :("

**Comment by sviatoslav-lebediev** [comment]
Hi, this add-on doesn't work with "short" links, try to open that deck link and use the final one.
p.s. it should be https://quizlet.com/804212449/ethics-flash-cards/?x=1jqt

**Comment by sviatoslav-lebediev** [comment]
I will close this ticket, re-open it, or create a new one if you still can't import decks.

**Comment by nmeshkati** [comment]
Thank you so much! It worked, you are super helpful.
