### ISSUE TITLE
Anki Quizlet importer no longer working. Error Code and link to deck provided.

### ISSUE THREAD

**Issue by atombums** [sviatoslav-lebediev/anki-quizlet-importer-extended#84]
Anki Importer is no longer working.

(https://quizlet.com/804325011/emed-block-1-diabetic-ketoacidosis-flash-cards/?funnelUUID=969a0164-2e52-4f30-a934-1f80023e0ca9)

The error code is massive and exceeds the character limit allowed in the body. The first part of the error from the addon window:
Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Captcha Challenge…</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAlNJREFUOE9VUz1IVWEYfp7vemkwMVpqlIKGiExFAxvUc0loCSqPNwJBshwatKUpGoL2rKbkolKTd3DISaGrEA32YxnZ1O/WJIYU5vV&#43;T3w/52JnuOfynvd9/t7vI/Y8BNA3qHYIowASQS0AQeg7gSUZPq7McrU&#43;QvfNTQno71fjbrMeSRx2dQpuFpJAuibACgIxtX9bY/PzuT&#43;u5j/1D9nG6jYXAXR7vDhcZ1JodOXwgxf5LZxbWDC/PXQyYKdBDodJD7sGYcLksGKtnKAuAGMS2rxi36PpSjl3lYWi7YTliuAbHcHMr68YXX1rqk5xJrO93eabj3AS0HDIBUJNp9mX2hKBkdDLtc2D6Hw3yapiNpHO59Fx3eabN/AGxElHJaLEJNVnAEedfBmOLJU55aG8GpdZ0BzUEL2pHTFAKRr5wmRAV

**Comment by sviatoslav-lebediev** [comment]
Hi, please try to import a few times, for some reason, quizlet blocks sometimes request.

**Comment by sviatoslav-lebediev** [comment]
@maf654321 maybe you can try to make this deck public, import and make it private again?

**Comment by sviatoslav-lebediev** [comment]
I'm going to try to fix this but I need time, if you guys know how it can be fixed let me know or create a PR.
So far it looks like I will need to add a service with a real browser and this service will fetch the required data.

**Comment by giulia1235** [comment]
I've the same error too now, do you know how long it will take to fix it? it was a massive help for studying  TnT

**Comment by sviatoslav-lebediev** [comment]
@giulia1235 do you have a problem with private decks or with a captcha ?
If it's a private deck issue - I would try to make it public for a short period of time
If it's a captcha issue - try to import a few times.

p.s. as for the fixing time, I will try to do something this evening, it's not my main job, so I need to find time :)

**Comment by Smankus** [comment]
Hi, Im receiving the same error and reattempting multiple times was working for awhile but is not any longer. Any estimate for when you have the new add on up and running?

This add on has single handedly been getting me through pa school.

**Comment by sviatoslav-lebediev** [comment]
@Smankus could you try to import now ? I've added a few more proxies and now I can import decks. If you can't pls provide the deck url.

**Comment by giulia1235** [comment]
regarding my decks, they are all public decks so I think it's a captcha issue(?) I saw the same error as the first person: "expecting value: line 1 column 1 (char 0)"

**Comment by sviatoslav-lebediev** [comment]
@giulia1235 I can't help you without deck links. I've bought more proxies and I see now that users can import decks (we still have some errors as well). I would try to change network connections if it's possible.

**Comment by MusmanK01** [comment]
Hi,
i am getting the same error no matter how many times I try to import with every deck. this is the most recent one I tried with. what is the estimated fix time? i need to study for my exam. 

https://quizlet.com/ca/703265462/pcat-chapter-1-laboratory-flash-cards/?funnelUUID=40188528-cd19-40e8-9aba-79ed951cdcd6

**Comment by sviatoslav-lebediev** [comment]
@MusmanK01 Hi, I've tried to import your deck using this URL https://quizlet.com/ca/703265462/pcat-chapter-1-laboratory-flash-cards, on the 3rd time the import was successful. Try to change your wifi network if it's possible. I've added more proxies, as I can see now users can import more decks. As for the 100% fix right now it looks too costly. I hope on Saturday I will have more time and will find a way how to fix this without spending a lot of money.

here is your deck
[PCAT Chapter 1 - Laboratory.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11563507/PCAT.Chapter.1.-.Laboratory.apkg.zip)

p.s. if you have more decks that you need to import - post them here and I will try to import them for you

**Comment by MusmanK01** [comment]
Hi,
Thank you! All of the sets I wanted to import worked! I just had to try it multiple times, or change the link, or wait a few minutes.

**Comment by sviatoslav-lebediev** [comment]
@MusmanK01 happy to hear this, yep it's not ideal but I hope in a few days I will find out how to fix the issue.

**Comment by sviatoslav-lebediev** [comment]
I've added the ability to set Quizlet HTML manually. Try this approach and let me know if it works for your case. I will close this ticket, re-open it, or create a new one if you still can't import decks.
