### ISSUE TITLE
i have been trying to import same deck for an hour

### ISSUE THREAD

**Issue by ajspecial** [sviatoslav-lebediev/anki-quizlet-importer-extended#85]
**Describe the bug**
I have been trying same deck for an hour i am still gettng this message can you please fix this why has this add on not being performed well its a basic concept and i dont think quizlet cares whats being used by anki
Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Captcha Challenge…</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAlNJREFUOE9VUz1IVWEYfp7vemkwMVpqlIKGiExFAxvUc0loCSqPNwJBshwatKUpGoL2rKbkolKTd3DISaGrEA32YxnZ1O/WJIYU5vV&#43;T3w/52JnuOfynvd9/t7vI/Y8BNA3qHYIowASQS0AQeg7gSUZPq7McrU&#43;QvfNTQno71fjbrMeSRx2dQpuFpJAuibACgIxtX9bY/PzuT&#43;u5j/1D9nG6jYXAXR7vDhcZ1JodOXwgxf5LZxbWDC/PXQyYKdBDodJD7sGYcLksGKtnKAuAGMS2rxi36PpSjl3lY

**Quizlet deck URL**

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Hi, could you please provide a deck link ?

**Comment by ajspecial** [comment]
https://quizlet.com/gb/804337532/musculoskeletal-16-bone-and-joint-infection-dave-hillier-flash-cards/?funnelUUID=b9273ba6-8bf8-4579-ab57-f8b8e4d5468b please fix your add on

**Comment by sviatoslav-lebediev** [comment]
I will try :)
for now, here is your deck (I could import it after 3 retries)

[Musculoskeletal 16. Bone and Joint Infection - Dave Hillier.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11576529/Musculoskeletal.16.Bone.and.Joint.Infection.-.Dave.Hillier.apkg.zip)

p.s. if you urgently need other decks send me links and I will try to import them

**Comment by sviatoslav-lebediev** [comment]
I've added the ability to set Quizlet HTML manually. Try this approach and let me know if it works for your case. I will close this ticket, re-open it, or create a new one if you still can't import decks.
