### ISSUE TITLE
Unknown Error Can't Import Quizlet

### ISSUE THREAD

**Issue by orvpagadua** [sviatoslav-lebediev/anki-quizlet-importer-extended#87]
Can't import Quizlet. Expecting value: line 1 column 1 (char 0)

**Quizlet deck URL**
https://quizlet.com/769798091/aca-developer-flash-cards/

https://quizlet.com/_cqbg0b?x=1jqt&i=4asnij

**Additional context**
error message copied and attached below
[Quizlet error.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11651593/Quizlet.error.txt)

**Comment by sviatoslav-lebediev** [comment]
Hi, could you please take a look at https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/86#issuecomment-1570860739 ?

**Comment by sviatoslav-lebediev** [comment]
+ this link format the add-on doesn't support `https://quizlet.com/_cqbg0b?x=1jqt&i=4asnij` it should have a long format `https://quizlet.com/769798091/aca-developer-flash-cards/`

**Comment by orvpagadua** [comment]
Hello. tried both links and video tutorial on #86 comment. it didn't work.

**Comment by sviatoslav-lebediev** [comment]
@orvpagadua could you please provide a quizlet link + error that you have got?

**Comment by orvpagadua** [comment]
it just says 'Unknown'.

**Comment by sviatoslav-lebediev** [comment]
hm, I would double-check that you paste the correct HTML from the right page (it should be https://quizlet.com/769798091/flashcards for your deck). HTML version should work, try to uncheck `Download audio` + check `Skip errors`

**Comment by orvpagadua** [comment]
been there done that. still error unknown.

**Comment by sviatoslav-lebediev** [comment]
hm, I've tried to import your deck, I don't see any issues.

[ACA Developer.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11690264/ACA.Developer.apkg.zip)

**Comment by orvpagadua** [comment]
That's great. but I just ended up manually copying the deck. thanks anyways.

**Comment by sviatoslav-lebediev** [comment]
@orvpagadua sorry to hear that. I would take a look at this comment https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/86#issuecomment-1584820494 .
