### ISSUE TITLE
Quizlet won't import

### ISSUE THREAD

**Issue by alleila22618** [sviatoslav-lebediev/anki-quizlet-importer-extended#88]
Like many others, I am having difficulties with the quizlet anki importer. 

Here is a deck I've tried to import:
https://quizlet.com/808172083/cdo-rsh-menopause-flash-cards/?funnelUUID=0336e467-9452-4514-8d10-27b57e38ebd8

I've gotten the same (huge) error whether I use the html or not: "Expecting value: line 1 column 1 (char 0)"

**Comment by aalberts28** [comment]
I have the same error with this deck: 

https://quizlet.com/808339452/respiratory-pathology-flash-cards/?funnelUUID=a7c45ec8-90e4-42c4-9b18-1218774592de

**Comment by sviatoslav-lebediev** [comment]
@aalberts28 your deck is private, maybe you can make it public temporary or try to use the HTML mode

**Comment by sviatoslav-lebediev** [comment]
@alleila22618 have you tried this https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/86#issuecomment-1570860739 ?
