### ISSUE TITLE
Saying it's behind a captcha, but do not have a VPN

### ISSUE THREAD

**Issue by jag7dr** [sviatoslav-lebediev/anki-quizlet-importer-extended#9]
The specific quizlet I'm trying to upload is https://quizlet.com/149857023/antimicrobials-flash-cards/ 
I'm not sure what else I can do to solve this issue?

**Comment by sviatoslav-lebediev** [comment]
I've successfully downloaded your deck. Do you use this addon https://ankiweb.net/shared/info/1362209126 ?
Have you configured it as described here https://ankiweb.net/shared/info/538351043 ?

**Comment by jag7dr** [comment]
I used the Quizlet to Anki Importer with Audio Support and I tried configuring it by setting qlts and it is getting the same error. I experimentally tried using the Quizlet to Anki Importer (without audio support) and I received the same message.

**Comment by sviatoslav-lebediev** [comment]
do you have any firewalls? what OS do you use? maybe you can copy/paste here your plugin configuration?

**Comment by jag7dr** [comment]
I'm not sure what exactly was happening, but I eventually switched the wifi I was on and the message disappeared. Thank you so much for your help!

**Comment by sviatoslav-lebediev** [comment]
cool, happy you could find a way to solve the problem
