### ISSUE TITLE
Error code after uploading Quizlet HTML, stops uploading halfway

### ISSUE THREAD

**Issue by jimportante** [sviatoslav-lebediev/anki-quizlet-importer-extended#91]
I'm still having problems despite my ability to copy the copy the Quizlet HTM. Now, it will upload halfway and then give me an error message like this: 

"Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.63 (f356f177) Python 3.9.15 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-12.3-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-06-10 10:57:04
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

How can I fix this?

**Comment by sviatoslav-lebediev** [comment]
Hi, try to check a `Skip errors` checkbox. And next time please provide a quizlet deck that you are trying to import
