### ISSUE TITLE
Can't get to import quizlet deck for the life of me

### ISSUE THREAD

**Issue by ashc118** [sviatoslav-lebediev/anki-quizlet-importer-extended#92]
**Describe the bug**
I'll preface this by saying I am not very technologically adept and have only ever just made my own anki decks before. I tried following the suggestions on this page https://ankiweb.net/shared/info/1362209126 but no matter what I tried to do nothing works. I tried opening the deck in an incognito mode, clicking on the flashcards page source and copying the html, didn't work. I tried changing my wifi from my main wifi to my phone's, didn't work. I tried setting the qlts from the cookies, didn't work. Since the deck I'm importing is rather large, I tested a smaller set, didn't work. I just don't know what to do and can't rule out that it's me being bad at this kind of stuff, but I would really like to figure out how to upload this anki deck. I've tried this a few times over the course of several days and I keep getting the Expecting value: line 1 column 1 (char 0) error. 

**Quizlet deck URL**
https://quizlet.com/716518010/normal-animal-exam-1-flash-cards/

**Additional context**
Expecting value: line 1 column 1 (char 0) error

**Comment by sviatoslav-lebediev** [comment]
Hi, it's not your fault :) It looks like quizlet has changed something again :) I need time to fix the add-on. Will ping you when it's done

**Comment by sviatoslav-lebediev** [comment]
@ashc118 please update the add-on and try one more time

**Comment by ashc118** [comment]
It worked perfectly!! Thank you sooooooooo much!!!!!!! :)
