### ISSUE TITLE
*help* Unable to import a deck... 

### ISSUE THREAD

**Issue by tclxy194** [sviatoslav-lebediev/anki-quizlet-importer-extended#93]
"unknown error" shows up when I try to import a deck from quizlet to anki. I've also tried to copy/paste html

When I hit import Deck, the process seems to be stuck on "Connecting to Quizlet..."

[**Quizlet deck URL**](https://quizlet.com/454735980/columbia-bartending-agency-flash-cards/)

**Additional context**
Error from the addon window
Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Captcha Challenge…</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/..."

**Comment by tclxy194** [comment]
I also tried the "skip error"

**Comment by sviatoslav-lebediev** [comment]
sorry I haven't seen your message. Please update the add-on and try one more time

**Comment by tclxy194** [comment]
It works now! Thank so much!
