### ISSUE TITLE
*New Anki User    Plz help me fix this Addon issue

### ISSUE THREAD

**Issue by PlzFixMyAnkiQuizletAddon** [sviatoslav-lebediev/anki-quizlet-importer-extended#95]
**Describe the Bug**

Expecting value: line 1 column 1 (char 0)
-------------------

I have the problem of not being able to import this (URL below) or any Quizlet decks
i have read other issues here and watched your videos(about copying the html) and some other videos but it still doesn't work
I use a Windows PC (Windows 11, up-to-date in updates), not a Mac. (I don't know if that is important)

**Quizlet URL link** (below)
https://quizlet.com/gb/810408111/gsce-biology-topic-1-cell-biology-flash-cards/?funnelUUID=3bfafa8c-6284-472d-9990-bc37b8e0c0eb

**Additional context**
<img width="763" alt="Screenshot 2023-06-15 212704" src="https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/136754644/ef0b237e-4f9e-43cc-8ade-58edeb56ea58">

**Comment by baroxyton** [comment]
I have the same problem here; not a fix, but I made a small script as a temporary replacement:

```js
document.body.innerText = Array.from(document.querySelectorAll(".SetPageTerm-contentWrapper")).map(element => {
    return `"${element.querySelector(".SetPageTerm-wordText").innerText.replaceAll('"', '""')}","${element.querySelector(".SetPageTerm-definitionText").innerText.replaceAll('"', '""')}"`
}).join("\n")
```

instructions: 1. open the desired quizlet set on the main/start page. Make sure that all terms are shown by scrolling all the way down and selecting 'show more'


![2023-06-15_23-25](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/69308275/a740fd2e-1ab9-4c6a-98b2-88caabb5a7e2)

step 2: run the script in the developer console; now, you should have the terms in a clean CSV format

![2023-06-15_23-27](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/69308275/878cb15d-181b-4375-8680-2f1e199c475a)



step 3: copy all of the CSV from the website and paste it into notepad. When saving, check the option to allow all file types and set the extenion to .csv. If you've done anything right, you should now end up with a .csv file with all of the terms and definitions. Lastly, click the inbuilt import file option and import your data, default import configuration should work

hope this works until the importer is fixed!

**Comment by sviatoslav-lebediev** [comment]
Hi, it looks like Quizlet has changed something again :) I need time to fix the add-on. Will ping you when it's done

**Comment by sviatoslav-lebediev** [comment]
I've updated the addon, try to update it and check if it works for you.

**Comment by sviatoslav-lebediev** [comment]
I'm going to close this issue, create a new one if you still can't import
