### ISSUE TITLE
Quizlet to Anki importer not working 

### ISSUE THREAD

**Issue by ananyar18** [sviatoslav-lebediev/anki-quizlet-importer-extended#97]
Hi, sorry for this - the importer isn't working on my 2020 MacBook Air- it was working until yesterday and then suddenly stopped. How would you suggest fixing this? Thank you.

**Comment by sviatoslav-lebediev** [comment]
Hi, it looks like quizlet has changed something again :) I need time to fix the add-on. Will ping you when it's done

**Comment by ananyar18** [comment]
No worries thank you!
________________________________

**Comment by MrBruhhman** [comment]
I think its because quizlet links now have an extra set of letters in the URL.

**Comment by ananyar18** [comment]
That makes sense, thank you.

________________________________

**Comment by sviatoslav-lebediev** [comment]
I've updated the addon, try to update it and check if it works for you.

**Comment by jby25** [comment]
It says sorry, this is a private deck. Im not sure how you configure the cookies or qlts. the instructions were confusing

**Comment by sviatoslav-lebediev** [comment]
@jby25 hm, I can't help you if you don't send the deck URL :)

**Comment by jby25** [comment]
https://quizlet.com/810006495/4-ag-presentation-flash-cards/?funnelUUID=79db459d-4540-4c16-9f3a-974cd811e4f7

**Comment by sviatoslav-lebediev** [comment]
@jby25 hm, I don't see any issues with importing your deck. Have you updated the add-on ? Because anki has not told be that there is a new version of the add-on. You can try to install it from here https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/releases/tag/v2023.06.18

[4. Ag Presentation.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11781750/4.Ag.Presentation.apkg.zip)

**Comment by jby25** [comment]
Thank you so much, that worked! :)

**Comment by MusmanK01** [comment]
Hey! i am having issues with importing my decks again. i also honestly don't understand what I am suppose to copy when I click "view page source" to get the html

https://quizlet.com/22062856/8-strong-acids-and-8-strong-bases-flash-cards/
https://quizlet.com/13182610/polyatomic-ions-flash-cards/
https://quizlet.com/207574580/acs-organic-chemistry-ii-final-examination-flash-cards/?funnelUUID=dcf4b027-bb23-4fe7-a86c-9de5fe4149bc
https://quizlet.com/114656144/oc-strong-nucleophiles-bases-e1-e2-sn1-sn2-flash-cards/

**Comment by sviatoslav-lebediev** [comment]
@MusmanK01 here is a video https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/86#issuecomment-1570860739 
Try to watch and let me know if it helps

**Comment by MusmanK01** [comment]
when i click view page source theres way more information on that page than shown in the video. i copied it and pasted it and it still didn't work. i tried it with the first link maybe if you can try it and send a video or screenshot of what you see.
Thank you!

**Comment by sviatoslav-lebediev** [comment]
@MusmanK01 here is a video with the first link

https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/87317c71-58d4-40a8-b346-b04d93b447dd


you also can just open your link and click on the `Flashcards` button, it will open the same link as the 'Open html' one

![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/9e3c3137-d0a5-493a-b4ab-cc039a248966)


p.s. maybe you can add your video and I will tell you what's wrong ?

**Comment by ananyar18** [comment]
Thank you so much it works now!

Thank you!
________________________________

**Comment by MusmanK01** [comment]
when i tried the same thing it had the same error. but now after the update it is working correctly. Thank you so much!

**Comment by sviatoslav-lebediev** [comment]
going to close this issue, if somebody still can't import decks, please create a new issue
