### ISSUE TITLE
Error with Importing Quizlet Flashcards

### ISSUE THREAD

**Issue by BelovedSemicolon** [sviatoslav-lebediev/anki-quizlet-importer-extended#99]
**Describe the bug**
I'm unable to to import the Quizlet flashcards into Anki. This error happened after I force quit Anki because I waited 5 minutes for it to begin importing the cards. I checked to see if the add-on is up-to-date and it is. I really love this add-on and it has saved me so much time and effort in creating flashcards.

**Quizlet deck URL**
https://quizlet.com/300835346/dli-russian-mod-1-lesson-2-flash-cards/

**Additional context**
Error from the addon window

Expecting value: line 1 column 1 (char 0)
-----------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Captcha Challenge…</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAlNJREFUOE9VUz1IVWEYfp7vemkwMVpqlIKGiExFAxvUc0loCSqPNwJBshwatKUpGoL2rKbkolKTd3DISaGrEA32YxnZ1O/WJIYU5vV&#43;T3w/52JnuOfynvd9/t7vI/Y8BNA3qHYIowASQS0AQeg7gSUZPq7McrU&#43;QvfNTQno71fjbrMeSRx2dQpuFpJAuibACgIxtX9bY/PzuT&#43;u5j/1D9nG6jYXAXR7vDhcZ1JodOXwgxf5LZxbWDC/PXQyYKdBDodJD7sGYcLksGKtnKAuAGMS2rxi36PpSjl3lYWi7YTliuAbHcHMr68YXX1rqk5xJrO93eabj3AS0HDIBUJNp9mX2hKBkdDLtc2D6Hw3yapiNpHO59Fx3eabN/AGxElHJaLEJNVnAEedfBmOLJU55aG8GpdZ0BzUEL2pHTFAKRr5wmRAVRINrkGGp5ZmuZaR198xQLeZnqJajcX7AKCqA9gGtM9rNOiolN2e4&#43;h/NkK1J7UdRnQ2nKwdZ2EdwHG/Z2p8uWwe&#43;lZH54LwDuJ2RBRSOy5gwhsUPzEZtPch3oxt33b&#43;qvXlM7NVJ9/j48x527Qvjw&#43;gWuLGHrBQ1DFZfASQD&#43;vFYq0JxeUZbjriLMzeC/aAaWAZ0Flfk3YFnvAhJ5d0D8TtGLdD&#43;UmxJINXQYC6IF4DdDgDBPja1nDRO0xT5TaAJxKuePvZ4uQuRcw7rtQd1uyiSJrLDiZw15pknbdgcQdEYzaWwfljTlYZrcbrMucJwiEM/wqXdQg1DElKILa4cg34AaBC6CnFNgA3SHVLfP4PI2gOacTNpN0AAAAASUVORK5CYII="/>

**Comment by sviatoslav-lebediev** [comment]
Hi, I would try to use some VPN or try to use a "Page HTML" mode 

[DLI Russian Mod 1 Lesson 2.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11786486/DLI.Russian.Mod.1.Lesson.2.apkg.zip)
